/* 책의 모든 글. 화면 코드는 없다. 원본: rohitg00/ai-engineering-from-scratch (MIT, 확인일 2026-10-08)의 Phase 13을 한국어로 재구성했다. 원문과 코드를 옮기지 않았다. */
window.A14Book=(()=>{
const RAW='https://github.com/rohitg00/ai-engineering-from-scratch/tree/main/phases/13-tools-and-protocols/';
const L=(slug,title,what)=>[`원본 레슨 ${slug.slice(0,2)} · ${title}`,RAW+slug,what];
return {
meta:{
 short:'도구와 프로토콜',title:'도구와 프로토콜 · 함수 호출에서 MCP와 스킬까지',eyebrow:'AI ENGINEERING FROM SCRATCH / 14',
 hero:['모델이 세상에 손을 뻗는','계약을 한 겹씩 세웁니다.'],
 lead:'팀 회의 노트를 찾고, 요약하고, 정리하는 노트 비서를 처음부터 만듭니다. 모델이 도구를 부탁하는 네 단계에서 출발해, 요청 한 통마다 필요한 것을 모두 담는 MCP, 사람에게 되묻는 확인, 오래 걸리는 작업, 토큰과 게이트웨이, 스킬까지 계약을 하나씩 더합니다. 장마다 그 계약이 막아 주는 실패를 직접 일으켜 봅니다.',
 feature:['envelope','MCP 요청 검사 순서 따라가기'],stat:['31','원본 레슨 재구성'],
 flowTitle:'노트 비서 하나를 끝까지 만듭니다',flowLead:'노트 비서는 한 앱 안의 함수 호출에서 시작해, 여러 MCP 서버와 게이트웨이를 거쳐, 스킬로 포장된 절차까지 자랍니다.',
 flow:['도구 호출|모델이 부탁하고 호스트가 실행한다','MCP 요청|요청 한 통에 버전과 기능을 담는다','되묻기와 긴 작업|확인, 작업 핸들, 취소를 나눈다','신뢰와 운영|설명·토큰·게이트웨이·트레이스를 검증한다','스킬과 종합|절차를 포장하고 사고를 조사한다'],
 paths:[
  {title:'함수 호출에서 MCP까지',desc:'도구 계약과 MCP 요청의 기본 모양을 순서대로 익힙니다.',chapters:['loop','schema','envelope','client']},
  {title:'MCP 서버를 운영해야 한다면',desc:'요청 검사, 되묻기, 긴 작업, 토큰, 게이트웨이를 차례로 다룹니다.',chapters:['envelope','mrtr','tasks','auth','gateway']},
  {title:'에이전트를 안전하게 만들고 싶다면',desc:'도구 설명, 공급망, 스킬 권한을 보고 마지막 사고 조사로 확인합니다.',chapters:['schema','poison','skills','final']}
 ],
 sourcesLead:'원본 커리큘럼 AI Engineering from Scratch의 Phase 13(도구와 프로토콜) 레슨 31개를 읽고, 개념과 순서만 참고해 한국어로 새로 썼습니다. 각 장의 “더 읽어 보기”에 원본 레슨 폴더와 레슨이 인용한 명세를 두었습니다. MCP 2026-07-28 개정판, A2A 1.0.1, 제공자와 호스트의 동작과 한도는 원본 커리큘럼 기준(확인일 2026-10-08)이며 명세가 바뀌면 달라질 수 있습니다.',
 note:'<strong>실험의 경계</strong><br>이 책의 실험은 실제 서버나 모델을 부르지 않습니다. 원본 레슨이 정한 규칙(스키마 검사, 요청 검사 순서와 오류 코드, 캐시 범위, requestState 검사 순서, 작업 상태, 두 시계, 서술자 정규화와 해시, 토큰 검사 순서, 정밀도·재현율 기준)은 브라우저 안에서 실제로 계산합니다. 지연 시간, 토큰 수, 점검 시간, 라우팅 점수 같은 숫자는 교육용 가정값이나 미리 정한 시나리오이며, 실험마다 결과 문장에 어느 쪽인지 밝혔습니다. 도구 지연 400·600·800ms, 유휴 500ms·최대 2000ms, 목록 항목 약 100토큰처럼 원본 레슨에 있는 값은 그대로 썼습니다.',
 glossary:[
  ['도구 호출 (tool call)','모델이 도구 이름과 인자를 담아 내보내는 구조화된 요청. 실행은 호스트가 합니다.'],
  ['JSON 스키마 (JSON Schema)','인자와 결과의 모양을 적는 규칙 언어. 이 책은 2020-12 판을 기준으로 합니다.'],
  ['MCP (Model Context Protocol)','도구·자원·프롬프트를 여러 모델과 앱이 같은 방식으로 쓰게 하는 프로토콜.'],
  ['JSON-RPC','요청에 id를 붙여 응답과 짝짓는 메시지 형식. id가 없으면 응답을 받지 않는 알림입니다.'],
  ['_meta','MCP 요청의 params 안에서 프로토콜 버전과 클라이언트 기능을 담는 자리.'],
  ['MRTR (Multi Round-Trip Request)','서버가 입력이 더 필요하다고 답하면, 클라이언트가 원래 요청을 새 id로 다시 보내는 방식.'],
  ['작업 핸들 (task)','오래 걸리는 일을 가리키는 taskId. 어느 복제본이든 같은 저장소에서 상태를 읽습니다.'],
  ['대상 (aud)','토큰이 어느 서버를 위해 발급되었는지 적은 주장. 다른 서버를 위한 토큰은 거절합니다.'],
  ['게이트웨이 (gateway)','여러 MCP 서버 앞에서 인증·정책·이름공간·감사를 맡는 하나의 문.'],
  ['스킬 (Agent Skill)','SKILL.md를 입구로 하는 절차 꾸러미. 목록에는 이름과 설명만 올라갑니다.']
 ],
 series:{name:'AI 엔지니어링 처음부터',no:14,total:20,prev:['../aie-multimodal/','멀티모달 AI'],next:['../aie-agents/','에이전트 엔지니어링']}
},
sources:[
 ['AI Engineering from Scratch (원본 커리큘럼, MIT)','https://github.com/rohitg00/ai-engineering-from-scratch','이 시리즈가 단계와 레슨 순서를 참고한 공개 저장소. 문장과 코드는 옮기지 않고 새로 썼다.'],
 ['원본 Phase 13 · Tools & Protocols',RAW.slice(0,-1),'이 책 전체가 재구성한 단계. 레슨 31개.'],
 L('01-the-tool-interface','The Tool Interface','설명·결정·실행·관찰 네 단계, 순수 도구와 결과가 남는 도구, 반복 상한.'),
 L('02-function-calling-deep-dive','Function Calling Deep Dive','OpenAI·Anthropic·Gemini의 선언·호출·결과 모양 비교와 번역기.'),
 L('03-parallel-and-streaming-tool-calls','Parallel and Streaming Tool Calls','병렬 호출의 id 짝짓기, 스트리밍 인자 조립, 400·600·800ms 비교.'),
 L('04-structured-output','Structured Output','JSON Schema 2020-12, 제약 디코딩, 세 가지 실패와 재시도.'),
 L('05-tool-schema-design','Tool Schema Design','이름·설명·매개변수 규칙, 원자적 도구, 설명 린터.'),
 L('06-mcp-fundamentals','MCP Fundamentals','상태 없는 요청, _meta, server/discover, 요청 검사 순서.'),
 L('07-building-an-mcp-server','Building an MCP Server','상태 없는 노트 서버, 결정적 목록, 캐시 힌트, stdio 규칙.'),
 L('08-building-an-mcp-client','Building an MCP Client','발견, 옛 시대로 내려가는 조건, 이름 충돌 병합과 길 찾기.'),
 L('09-mcp-transports','MCP Transports','stdio와 POST 전용 Streamable HTTP, 헤더 일치, 복제본에 숨은 상태.'),
 L('10-mcp-resources-and-prompts','MCP Resources and Prompts','도구·자원·프롬프트 나누기, cacheScope, subscriptions/listen.'),
 L('11-mcp-sampling','MCP Sampling','샘플링 폐기 예정과 MRTR, 서명된 requestState.'),
 L('12-mcp-roots-and-elicitation','MCP Roots and Elicitation','명시적 범위, 양식 확인, accept·decline·cancel, nonce.'),
 L('13-mcp-async-tasks','MCP Async Tasks','Tasks 확장, tasks/get·update·cancel, 작업 상태와 실패의 두 층.'),
 L('14-mcp-apps','MCP Apps','ui:// 자원, 샌드박스 iframe, ui/initialize 다리, 대체 경로.'),
 L('15-mcp-security-tool-poisoning','MCP Security: Tool Poisoning','일곱 공격 면, 서술자 고정, 스캐너, 이름공간, 둘의 규칙.'),
 L('16-mcp-security-oauth-2-1','MCP Security: OAuth 2.1','보호 자원 메타데이터, CIMD, PKCE, iss 확인, 범위 상향.'),
 L('17-mcp-gateways-and-registries','MCP Gateways and Registries','상태 없는 게이트웨이의 요청 처리, 레지스트리 승인, 자격 증명 중개.'),
 L('18-mcp-auth-production','MCP Auth in Production','JWKS 다시 받기, aud 검증, 불투명 토큰, 폐기와 장애 정책.'),
 L('19-a2a-protocol','A2A Protocol','Agent Card, 작업 생명 주기, 메시지 부분과 산출물, 세 바인딩.'),
 L('20-opentelemetry-genai','OpenTelemetry GenAI','스팬 계층, 필수 속성, traceparent 전파, “3초와 30초” 사례.'),
 L('21-llm-routing-layer','LLM Routing Layer','모델 별칭, 대체 사슬, 비용 집계, LiteLLM·OpenRouter·Portkey 비교.'),
 L('22-skills-and-agent-sdks','Skills and Agent SDKs','SKILL.md 계약, 이웃 개념과의 구분, 스킬 생명 주기.'),
 L('23-capstone-tool-ecosystem','Capstone: Tool Ecosystem','모든 경계를 잇는 종합 과제와 흉내·실제 구분 표.'),
 L('24-skill-discovery-and-progressive-disclosure','Skill Discovery and Progressive Disclosure','발견 파이프라인, 세 단계 공개, 목록 예산, 경로 포함.'),
 L('25-skill-invocation-and-routing','Skill Invocation and Routing','다섯 호출 경로, 사람·모델 2×2, 자격 먼저 거르기, 근접 오답.'),
 L('26-skill-permissions-sandboxes-and-trust','Skill Permissions, Sandboxes, and Trust','권한 다섯 층, 위협 모형, allow·ask·deny, 격리 경계.'),
 L('27-skill-evals-packaging-and-portability','Skill Evals, Packaging, and Portability','여섯 평가 층, 정밀도·재현율, 출시 기준, 이식성 표.'),
 L('28-mcp-tool-contracts-and-content','MCP Tool Contracts and Content','출력 스키마, 다섯 content 종류, x-mcp-header, 빈 문자열 커서.'),
 L('29-mcp-reliability-cancellation-and-flow-control','MCP Reliability, Cancellation, and Flow Control','요청 취소와 작업 취소, 두 시계, 멱등 키, 흐름 제어.'),
 L('30-mcp-registry-supply-chain-and-drift','MCP Registry Supply Chain and Drift','이름공간 확인, 다이제스트 고정, 상태 동기화, 되돌리기 장부.'),
 L('31-mcp-conformance-versioning-and-operations','MCP Conformance, Versioning, and Operations','정상·거절 기록, 시대 분리, SDK 차이, 프록시 증거, 출시 문.'),
 ['MCP 명세 2026-07-28','https://modelcontextprotocol.io/specification/2026-07-28','원본 레슨들이 기준으로 삼은 상태 없는 MCP 개정판.'],
 ['MCP 2026-07-28 변경 기록','https://modelcontextprotocol.io/specification/2026-07-28/changelog','핸드셰이크와 세션 제거 등 이전 판과의 차이.'],
 ['MCP server/discover','https://modelcontextprotocol.io/specification/2026-07-28/server/discover','모든 서버가 구현하는 발견 메서드.'],
 ['MCP Streamable HTTP','https://modelcontextprotocol.io/specification/2026-07-28/basic/transports/streamable-http','POST 전용 엔드포인트, 헤더와 본문 일치 규칙.'],
 ['MCP Multi Round-Trip Requests','https://modelcontextprotocol.io/specification/2026-07-28/basic/patterns/mrtr','input_required 결과와 재시도 규칙.'],
 ['MCP Resources','https://modelcontextprotocol.io/specification/2026-07-28/server/resources','자원 목록·읽기와 -32602 규칙.'],
 ['MCP Tools','https://modelcontextprotocol.io/specification/2026-07-28/server/tools','도구 서술자, 결과 content, isError.'],
 ['MCP Tasks 확장 (초안)','https://tasks.extensions.modelcontextprotocol.io/specification/draft/tasks','tasks/get·update·cancel과 작업 상태.'],
 ['MCP Apps 개요','https://modelcontextprotocol.io/extensions/apps/overview','ui:// 자원과 iframe 다리.'],
 ['MCP 요청 취소','https://modelcontextprotocol.io/specification/2026-07-28/basic/patterns/cancellation','stdio 알림과 HTTP 스트림 닫기.'],
 ['MCP 인가','https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization','HTTP 전송의 OAuth 인가 프로필.'],
 ['RFC 9728 · OAuth Protected Resource Metadata','https://datatracker.ietf.org/doc/html/rfc9728','자원 서버가 믿는 인가 서버를 알리는 문서.'],
 ['RFC 8707 · Resource Indicators','https://datatracker.ietf.org/doc/html/rfc8707','토큰 요청의 resource 매개변수와 대상 묶기.'],
 ['RFC 9207 · Authorization Server Issuer Identification','https://datatracker.ietf.org/doc/html/rfc9207','인가 응답의 iss 확인으로 mix-up 공격 막기.'],
 ['RFC 7636 · PKCE','https://datatracker.ietf.org/doc/html/rfc7636','code_verifier와 S256 code_challenge.'],
 ['MCP 공식 레지스트리 server.json 요건','https://github.com/modelcontextprotocol/registry/blob/main/docs/reference/server-json/official-registry-requirements.md','이름공간과 게시 기록의 요건.'],
 ['MCP 적합성 시험 프로젝트','https://github.com/modelcontextprotocol/conformance','버전별 외부 적합성 시험.'],
 ['A2A 프로토콜','https://a2a-protocol.org/latest/','에이전트 사이 위임의 공식 문서.'],
 ['OpenTelemetry GenAI 의미 규약','https://github.com/open-telemetry/semantic-conventions-genai','gen_ai.* 속성과 스팬 이름. 옛 opentelemetry.io 페이지는 이 저장소로 옮겨졌다는 안내만 남아 있다(확인일 2026-10-08).'],
 ['LiteLLM 문서','https://docs.litellm.ai/','원본이 비교한 직접 운영형 라우팅 게이트웨이.'],
 ['Agent Skills 명세','https://agentskills.io/specification','SKILL.md 머리말과 점진적 공개.'],
 ['Agent Skills · 스킬 평가하기','https://agentskills.io/skill-creation/evaluating-skills','트리거와 행동 평가 안내.'],
 ['JSON Schema 2020-12 릴리스 노트','https://json-schema.org/draft/2020-12/release-notes','모든 도구 API가 쓰는 스키마 방언.'],
 ['MCP 기본 프로토콜','https://modelcontextprotocol.io/specification/2026-07-28/basic','JSON-RPC 봉투와 요청 메타데이터.'],
 ['OpenAI 함수 호출 안내','https://platform.openai.com/docs/guides/function-calling','tools·tool_calls 모양과 병렬 호출.'],
 ['Anthropic 도구 사용 개요','https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/overview','tool_use·tool_result 블록.'],
 ['Gemini 함수 호출','https://ai.google.dev/gemini-api/docs/function-calling','functionDeclarations와 병렬 호출 id.'],
 ['OpenAI 구조화된 출력','https://platform.openai.com/docs/guides/structured-outputs','엄격 모드의 스키마 조건과 거절.'],
 ['RFC 7662 · Token Introspection','https://datatracker.ietf.org/doc/html/rfc7662','불투명 토큰의 active·대상·범위 확인.'],
 ['MCP 페이지 나누기','https://modelcontextprotocol.io/specification/2026-07-28/server/utilities/pagination','불투명 커서와 nextCursor.'],
 ['MCP 캐시 힌트','https://modelcontextprotocol.io/specification/2026-07-28/server/utilities/caching','ttlMs와 cacheScope.'],
 ['MCP Elicitation','https://modelcontextprotocol.io/specification/2026-07-28/client/elicitation','양식 모드와 URL 모드, 세 가지 응답.']
],
info:{
 validate:['도구 인자 검사','노트 비서가 notes_search를 부를 때 모델이 만든 인자를 바꿔 가며, 스키마 검사가 어느 필드에서 어떤 오류를 내는지 봅니다.','additionalProperties: false를 빼면 지어낸 필드는 어떻게 될까요? 거절과 무시 중 무엇이 안전한지 말해 보세요.'],
 fanout:['순차 호출과 병렬 호출','부를 도구 수와 모델 왕복 시간을 바꾸며 두 방식의 벽시계 시간과 모델 왕복 횟수를 계산합니다.','모델 왕복이 0ms라면 병렬이 아낀 시간은 어디에서 나올까요?'],
 retry:['검사 후 재시도의 성공률','한 번 생성한 인자가 스키마를 통과할 확률과 최대 시도 횟수를 바꾸며 성공률과 기대 시도 횟수를 계산합니다.','통과 확률 0.85에서 3번까지 시도하면 1,000번 중 몇 번이 끝내 실패할까요?'],
 lint:['도구 설명 린터','노트 비서의 도구 초안을 골라 이름·설명·enum·쪼개기·중독 패턴 규칙으로 검사합니다.','만능 도구 manage_notes는 어떤 규칙에 걸릴지 먼저 예측해 보세요.'],
 lifecycle:['MCP 요청 검사 순서','요청에 결함 하나와 전송 방식을 고르면, 일곱 검사 단계 중 어디서 멈추고 어떤 코드로 답하는지 따라갑니다.','같은 “지원하지 않는 버전”이라도 헤더와 본문이 다르면 오류 코드가 어떻게 바뀔까요?'],
 replica:['복제본과 숨은 상태','복제본 수와 초안을 두는 방식을 바꾸며 다음 요청이 초안을 찾을 확률과 1,000번 중 실패 수를 계산합니다.','복제본이 1개일 때 메모리 설계가 멀쩡해 보이는 이유와, 그것이 왜 착시인지 말해 보세요.'],
 cache:['cacheScope와 ttlMs','지우와 민호가 같은 notes://inbox를 여덟 번 읽는 시나리오에서 캐시 범위와 유효 시간을 바꾸며 적중·누출·낡은 내용을 셉니다.','private로 바꾸면 누출은 사라집니다. 그런데 ttlMs를 60초로 늘리면 새로 생기는 문제는 무엇일까요?'],
 rebind:['MRTR 재시도 검증','지우기 확인을 다시 보낸 요청을 하나씩 변조하며, 어느 검사에서 멈추는지와 노트·nonce가 어떻게 되는지 봅니다.','decline과 cancel은 둘 다 노트를 지우지 않습니다. 둘의 차이는 무엇일까요?'],
 tasklife:['작업의 상태 변화','작업 이야기와 단계를 골라, 호출마다 resultType과 작업 status가 어떻게 갈리는지 한 단계씩 따라갑니다.','“늦은 취소” 이야기에서 tasks/cancel이 성공했는데도 결과가 completed인 이유는 무엇일까요?'],
 deadline:['유휴 시계와 최대 시계','진행 알림 간격과 작업 길이를 바꾸며 요청이 완료되는지, 어느 시계에 걸려 취소되는지 계산합니다.','진행 알림이 400ms마다 와도 작업이 2.5초 걸리면 어떻게 될까요?'],
 admit:['서술자 고정과 심사','export 서술자를 바꾸는 방식을 골라 다이제스트, 스캐너 경고, 심사 결정을 비교합니다.','스키마에 필드 하나만 늘어난 러그 풀은 스캐너에 걸릴까요, 다이제스트에 걸릴까요?'],
 token:['자원 서버의 토큰 검사','토큰의 주장 하나를 망가뜨리고 부를 도구를 골라, 어느 검사에서 몇 번 상태로 멈추는지 계산합니다.','노트 서버 토큰을 할 일 서버에 내밀면 iss와 aud 중 어느 검사에서 걸릴까요?'],
 trace:['트레이스 폭포','MCP 서버 상태와 trace 문맥 전파를 바꾸며 스팬 폭포와 설명되지 않는 시간을 봅니다.','전파를 끄고 콜드 스타트를 켜면, 노트 비서 쪽 트레이스에서 무엇을 알고 무엇을 모를까요?'],
 disclosure:['스킬 목록 예산','설치한 스킬 수와 문맥 창 크기를 바꾸며 목록 비용, 2% 예산에 들어가는 항목 수, 모두 올릴 때와 점진 공개의 토큰을 계산합니다.','128k 창에서 스킬이 300개면 몇 개의 설명이 목록에서 빠질까요?'],
 routeval:['라우팅 평가 기준','설명 판과 발동 문턱을 바꾸며 16개 사례의 혼동 행렬, 정밀도, 재현율, 출시 기준 통과 여부를 계산합니다.','v1에서 문턱을 올리면 정밀도와 재현율은 각각 어느 쪽으로 움직일까요?'],
 incident:['확인 순서 정하기','이상 보고와 확인 순서 전략을 바꾸며 원인을 드러내는 점검까지 걸리는 시간을 계산합니다.','“어떤 날만 30초” 보고에 선 위 기록부터 보면 몇 분이 걸릴까요? 시간부터 보는 순서와 비교해 보세요.']
},
chapters:[
{id:'loop',title:'모델이 행동을 부탁하는 네 단계',subtitle:'설명하고, 고르고, 실행하고, 관찰합니다. 모델은 부탁만 하고 실행은 호스트가 맡습니다.',desc:'글자만 만드는 모델이 어떻게 노트를 검색할까요?',group:'도구 호출',time:'16분',labs:['validate','fanout'],source:[2,3,4,57,58,59,1],thumb:['설명','호출','관찰'],
 paragraphs:[
 '이 책은 팀의 회의 노트를 찾고, 요약하고, 정리하는 노트 비서를 처음부터 만듭니다. 출발점의 문제는 단순합니다. 언어 모델이 내놓는 것은 다음 토큰의 확률뿐이어서, “지난주 배포 회의 노트를 찾아 줘”라는 말에 그럴듯한 문장은 쓸 수 있어도 노트 저장소를 직접 열 수는 없습니다. 그래서 노트 비서를 돌리는 호스트 프로그램이 notes_search 같은 도구 목록을 모델에게 알려 주고, 모델은 필요할 때 도구 이름과 인자를 담은 구조화된 호출을 내보냅니다. 호스트는 그 인자를 스키마로 검사한 뒤 도구를 실제로 실행하고, 결과에 같은 호출 id를 붙여 대화에 돌려줍니다. 원본 커리큘럼은 이 설명·결정·실행·관찰의 네 단계를 Phase 13 전체가 조금씩 덧붙여 가는 변하지 않는 뼈대라고 부릅니다.',
 'OpenAI, Anthropic, Gemini는 같은 고리를 서로 다른 필드 이름과 중첩으로 감쌉니다. 인자가 문자열로 오는지 객체로 오는지, 결과를 어떤 메시지에 담는지가 달라서, 원본 레슨 02는 도구 선언 하나를 세 형식으로 옮기는 번역기를 만듭니다. 여러 도구를 한 차례에 함께 부르는 병렬 호출은 모델 왕복을 줄여 기다리는 시간을 크게 줄이지만, 결과가 끝나는 순서대로 돌아오므로 호출 id로 짝을 맞춰야 합니다. 스트리밍으로 인자가 조각조각 도착할 때는 그 호출이 끝났다는 신호가 오기 전에 JSON을 해석하면 안 됩니다. 이 장의 실험에서는 모델이 만든 인자를 스키마로 검사해 보고, 도구 수와 모델 왕복 시간을 바꾸며 순차와 병렬의 차이를 계산합니다. 그런데 스키마를 통과할 인자를 모델이 처음부터 만들게 할 수는 없을까요?'],
 formula:'순차 = (n + 1)·L + Σtᵢ · 병렬 = 2·L + max tᵢ',formulaNote:'n은 도구 수, L은 모델 왕복 한 번의 시간, tᵢ는 도구 i의 실행 시간입니다. 순차는 도구마다 모델이 한 번씩 더 생각하고, 병렬은 한 차례에 모든 호출을 내보낸 뒤 결과를 받아 한 번만 더 생각한다고 가정했습니다. 도구 지연 400·600·800ms는 원본 레슨 03의 값이고, 넷째 이후 도구의 지연과 L은 교육용 가정값입니다. 스레드 스케줄과 직렬화 비용은 무시합니다.',
 flow:['설명|이름·설명·입력 스키마를 알린다','결정|답하기, 호출하기, 거절하기','실행|인자를 검사하고 도구를 돌린다','관찰|같은 id로 결과를 돌려준다'],
 details:[
 ['네 단계와 신뢰의 갈림','<ul><li><b>설명</b>: 호스트는 도구마다 이름, 한 문단 설명, JSON 스키마(2020-12) 입력을 선언합니다. 제공자는 이 선언을 자기 형식으로 시스템 프롬프트에 넣습니다.</li><li><b>결정</b>: 모델은 바로 답하거나, 도구 호출을 하나 이상 내보내거나, 엄격 모드에서 거절(refusal)을 냅니다. 호출에는 id, name, arguments 세 필드가 있습니다.</li><li><b>실행</b>: 호스트가 인자를 검사합니다. 틀린 인자는 바로 오류로 돌려주거나, 제약 파서로 고치거나, 검사 오류를 넣어 모델에게 다시 시킵니다.</li><li><b>관찰</b>: 결과를 같은 id의 도구 메시지로 붙이고 모델을 다시 부릅니다. 모델이 호출을 멈추거나 호스트의 반복 상한에 닿을 때까지 돌며, 원본은 운영 호스트가 이 상한을 대략 5~20번으로 둔다고 소개합니다.</li><li><b>순수 도구와 결과가 남는 도구</b>: 읽기만 하는 notes_search는 미리 불러도 안전하지만, notes_delete처럼 상태를 바꾸는 도구는 사용자 확인이나 권한으로 막아야 합니다.</li></ul>'],
 ['세 제공자의 모양 차이','<div class="table-wrap"><table><tr><th>항목</th><th>OpenAI</th><th>Anthropic</th><th>Gemini</th></tr><tr><td>스키마 필드</td><td><code>parameters</code></td><td><code>input_schema</code></td><td><code>parameters</code> (functionDeclarations 안)</td></tr><tr><td>호출 위치</td><td><code>tool_calls[]</code></td><td><code>content[]</code>의 tool_use</td><td><code>parts[]</code>의 functionCall</td></tr><tr><td>인자 형태</td><td>JSON 문자열</td><td>해석된 객체</td><td>해석된 객체</td></tr><tr><td>결과 짝짓기</td><td><code>tool_call_id</code></td><td><code>tool_use_id</code></td><td>functionResponse의 <code>id</code></td></tr></table></div><p>원본 커리큘럼은 요청당 도구 수 한도를 OpenAI 128개, Anthropic과 Gemini 64개로 소개합니다. 다만 2026-10-08에 확인한 세 제공자의 함수 호출 안내 문서에는 이 개수가 적혀 있지 않고, OpenAI 안내는 한 차례에 20개 미만을 권하는 정도이므로, 실제 한도는 쓰는 API의 참조 문서에서 다시 확인해야 합니다. 세 곳 모두 자동(auto), 반드시 호출(required·any), 호출 금지(none) 모드를 이름만 달리해 지원합니다.</p>'],
 ['병렬 호출과 스트리밍 조립','<p>병렬 호출에서는 결과가 끝나는 순서대로 와도 id만 맞으면 됩니다. 원본은 결과를 완료 순서대로 id와 함께 돌려주기를 권합니다. 앞 호출의 결과가 뒤 호출의 입력이 되거나(파일을 만든 뒤 쓰기), 하류 API의 속도 제한이 넉넉하지 않으면 병렬을 끕니다. 스트리밍에서는 호출마다 버퍼를 따로 두고 조각을 모으며, 그 호출의 끝 신호(OpenAI의 <code>finish_reason</code>, Anthropic의 <code>content_block_stop</code>)가 온 뒤에만 JSON을 해석합니다. 중괄호 개수 세기는 문자열 안의 괄호 때문에 완성 판정으로 믿을 수 없습니다.</p>']],
 warning:'모델이 도구를 실행한다고 생각하기 쉽지만, 모델은 호출을 부탁하는 JSON을 만들 뿐이고 실행과 권한 판단은 호스트의 몫입니다. 그래서 모델이 그럴듯한 인자를 냈더라도 호스트는 스키마 검사와 확인 절차를 건너뛰면 안 되고, 반복 상한 없이 고리를 돌려서도 안 됩니다.',
 quiz:['노트 비서가 세 노트 저장소를 병렬로 검색했더니, 호출 목록 순서와 달리 400ms짜리 결과가 가장 먼저 도착했습니다. 호스트가 할 일은?',['호출 목록 순서가 맞을 때까지 결과를 버리고 다시 부른다','도착한 순서대로 결과를 돌려주되 각 결과에 원래 호출 id를 붙인다','가장 늦게 끝난 결과 하나만 돌려준다'],1,'병렬 호출의 결과는 id로 짝지어지므로 도착 순서는 상관없습니다. 원본은 완료 순서대로 id를 명시해 돌려주기를 권합니다.'],
 cross:[['AI Book 12 · 도구를 쓰고 결과를 확인하기','../ai/#agents','에이전트가 요청·행동·관찰을 반복하는 큰 그림을 먼저 보고 오면, 이 장의 네 단계가 그 고리의 한 바퀴를 프로토콜 수준에서 쪼갠 것임이 보입니다.'],['컴퓨터 원리 07 · 반복하고 갈라지기','../computer/#programs','도구 호출 고리는 결과를 보고 다음 행동을 고르는 반복문입니다. 반복 상한이 왜 필요한지 기계 수준의 반복과 분기에서 확인할 수 있습니다.']]},

{id:'schema',title:'모델이 헷갈리지 않는 도구 계약 쓰기',subtitle:'스키마는 인자의 모양을, 이름과 설명은 도구를 고를 근거를 정합니다.',desc:'노트 비서가 엉뚱한 도구를 고르는 이유는 무엇일까요?',group:'도구 호출',time:'16분',labs:['retry','lint'],source:[5,6,60,55,1],thumb:['스키마','재시도','린트'],
 paragraphs:[
 '앞 장에서 호스트는 모델이 낸 인자를 스키마로 검사하고 틀리면 거절했습니다. 원본 레슨 04에 따르면 모델에게 그냥 JSON으로 답하라고 시키면 최상위 모델에서도 5~15% 정도는 괄호 누락, 끝의 쉼표, 틀린 타입, 지어낸 필드 같은 이유로 실패합니다. 이를 다루는 방법은 셋입니다. JSON으로 답해 달라고 부탁만 하는 방법, 생성한 뒤 해석하고 검사해서 틀리면 오류를 넣어 다시 시키는 방법, 디코딩하는 순간 스키마에 어긋나는 토큰을 아예 고르지 못하게 막는 제약 디코딩입니다. 제약 디코딩에서는 해석 오류와 스키마 위반이 사라지고, 남는 실패는 입력이 스키마에 맞지 않는다며 모델이 거절하는 경우 하나입니다. 원본은 거절을 실패가 아니라 따로 다뤄야 할 정상 결과로 봅니다.',
 '모양이 맞는 인자만으로는 부족합니다. 도구가 서른 개쯤 되면 모델은 매번 모든 설명을 읽고 하나를 골라야 하는데, 두 설명이 모두 “사람을 찾는다”라고만 쓰여 있으면 고를 근거가 없습니다. 원본 레슨 05는 이름과 설명만 고쳐도 도구 선택 정확도가 10~20%p 달라진 측정을 소개하고, snake_case의 동사-명사 이름, “~할 때 사용합니다. ~에는 쓰지 않습니다.”라는 두 문장 설명, 닫힌 값 집합의 enum, action 값이 셋을 넘으면 도구를 쪼개는 규칙을 제시합니다. 설명은 모델의 문맥에 그대로 들어가므로 숨은 지시가 섞인 설명도 걸러야 합니다. 이 장의 실험에서는 재시도 횟수와 성공률의 관계를 계산하고, 노트 비서의 도구 초안 다섯 개를 린터로 검사합니다. 하지만 이렇게 다듬은 도구를 여러 모델과 앱이 함께 쓰려면 무엇을 더 약속해야 할까요?'],
 formula:'k번 안에 성공할 확률 = 1 − (1 − p)ᵏ',formulaNote:'p는 한 번 생성한 인자가 스키마를 통과할 확률이고, 시도마다 독립이라고 가정했습니다. 실제로는 같은 입력에서 같은 실수를 되풀이하는 경우가 많아 독립 가정이 성공률을 부풀립니다. 원본은 재시도를 최대 3번으로 두고, 그 이상이 필요하면 스키마나 프롬프트가 잘못되었다는 신호로 봅니다. 제약 디코딩에서는 이 식 대신 거절 여부만 남습니다.',
 flow:['부탁|JSON으로 답해 달라고 한다','검사 후 재시도|해석·검증·오류를 넣고 다시','제약 디코딩|어긋나는 토큰을 가린다','린트|이름·설명·enum·중독 패턴'],
 details:[
 ['스키마 구성과 세 가지 실패','<ul><li><b>자주 쓰는 구성</b>: <code>type</code>, <code>properties</code>, <code>required</code>, <code>enum</code>, <code>minimum</code>·<code>maximum</code>, <code>minLength</code>·<code>maxLength</code>·<code>pattern</code>, <code>items</code>, <code>additionalProperties</code>.</li><li><b>OpenAI 엄격 모드의 추가 조건</b>: 모든 속성을 required에 넣고, 모든 곳에 <code>additionalProperties: false</code>를 두며, 풀리지 않은 <code>$ref</code>를 쓰지 않습니다. 어기면 요청 단계에서 400 오류가 납니다.</li><li><b>실패 세 가지</b>: 해석 오류(JSON이 아님), 스키마 위반(해석은 되지만 모양이 틀림), 거절. 앞의 둘은 엄격 모드에서 생기지 않고, 거절은 다시 시키지 않고 기록한 뒤 타입이 있는 결과로 돌려줍니다.</li><li><b>제약 디코딩의 세 기법</b>: 스키마로 유한 오토마타를 만들어 매 단계 어긋나는 토큰을 가리는 문법 기반 디코딩, JSON 파서를 함께 돌려 다음에 올 수 있는 토큰을 계산하는 방식, 초안 모델이 제안하고 검증기가 스키마를 강제하는 추측 디코딩.</li><li><b>언어 바인딩</b>: Python에서는 Pydantic이 클래스에서 스키마를 만들고, TypeScript에서는 Zod가 같은 일을 합니다.</li></ul>'],
 ['이름·설명·매개변수 규칙','<ul><li><b>이름</b>: snake_case, 동사-명사 순서, 시제 없이, 인자를 이름에 넣지 않습니다. 큰 목록에서는 <code>notes_search</code>처럼 이름공간 접두어를 붙입니다. 이름 바꾸기는 깨지는 변경이므로 새 이름으로 새 판을 냅니다.</li><li><b>설명</b>: “~할 때 사용합니다. ~에는 쓰지 않습니다.” 두 문장. 뒤 문장이 비슷한 이웃 도구와 갈라 줍니다. 1024자 이하로 쓰고, 입력 형식과 단위를 알려 줍니다.</li><li><b>매개변수</b>: 닫힌 값 집합은 enum으로, 꼭 필요한 것만 required로, id에는 pattern을 붙여 지어낸 값을 걸러 냅니다.</li><li><b>쪼개기</b>: <code>do_everything(action, target, options)</code> 같은 만능 도구는 원본 소개에 따르면 선택 정확도가 15~30% 나빠집니다. action 값이 셋을 넘으면 원자적 도구로 나눕니다.</li><li><b>오류 문장</b>: 오류는 모델이 읽으므로 “query가 필요합니다. 예: {&quot;query&quot;: &quot;배포&quot;}”처럼 다음 행동을 알려 주게 씁니다.</li></ul>']],
 warning:'제약 디코딩을 켜면 결과가 틀릴 수 없다고 생각하기 쉽습니다. 보장되는 것은 모양뿐입니다. 스키마에 맞는 note_id라도 존재하지 않는 노트일 수 있고, 입력이 스키마에 맞지 않으면 모델은 거절합니다. 값의 의미와 권한은 여전히 서버가 확인해야 합니다.',
 quiz:['노트 비서의 manage_notes(action, target, options) 도구는 action으로 list, search, create, delete 네 값을 받습니다. 원본의 규칙에 따른 가장 좋은 고침은?',['action 설명을 길게 늘여 1024자를 채운다','notes_list, notes_search, notes_create, notes_delete 네 원자적 도구로 나눈다','action을 enum 없이 자유 문자열로 둔다'],1,'action 값이 셋을 넘으면 도구를 쪼갭니다. 모델은 문자열을 해석하는 대신 이름으로 도구를 고르게 됩니다.'],
 cross:[['머신러닝 기초 08 · 정확도 97%의 함정','../aie-ml/#metrics','“도구 선택 정확도가 몇 %p 올랐다”는 주장을 읽으려면 무엇을 정답으로 세었는지, 틀린 경우가 어떤 종류인지 알아야 합니다. 혼동 행렬과 정밀도·재현율을 보고 오면 11장의 라우팅 평가도 쉬워집니다.']]},

{id:'envelope',title:'요청 한 통에 필요한 것을 모두 담기',subtitle:'MCP 2026-07-28에는 핸드셰이크가 없습니다. 요청마다 버전과 기능을 싣고, 서버는 정해진 순서로 검사합니다.',desc:'서버가 이전 요청을 기억하지 않으면 무엇이 달라질까요?',group:'MCP 프로토콜',time:'18분',labs:['lifecycle'],source:[7,8,33,56,35,34],thumb:['_meta','검사','결과'],
 paragraphs:[
 '앞 장에서 노트 비서의 도구는 이름과 설명과 스키마를 갖춘 계약이 되었습니다. 이제 이 도구들을 노트 비서만이 아니라 다른 앱과 다른 모델도 쓰게 하려고 노트 서버를 MCP(Model Context Protocol) 서버로 엽니다. MCP 서버는 세 가지를 내놓습니다. 모델이 고르는 행동인 도구(tools/list, tools/call), URI로 가리키는 내용인 자원(resources/list, resources/read), 사용자가 고르는 틀인 프롬프트(prompts/list, prompts/get)입니다. 메시지는 JSON-RPC 2.0 형식이어서 요청에는 id가 있고, 응답은 같은 id에 result나 error 하나를 담으며, id가 없는 메시지는 응답을 받지 않는 알림입니다. 원본 커리큘럼이 기준으로 삼는 2026-07-28 개정판의 가장 큰 변화는 initialize 핸드셰이크와 프로토콜 세션이 사라졌다는 점입니다.',
 '세션이 없으므로 모든 요청은 params._meta 안에 프로토콜 버전과 클라이언트 기능을 반드시 싣고, 클라이언트 정보는 권장 사항으로 싣습니다. 같은 프로세스가 연달아 서로 다른 클라이언트의 요청을 받더라도, 서버는 앞 요청이 밝힌 기능을 다음 요청에 빌려 쓰면 안 됩니다. 서버는 server/discover를 반드시 구현해 지원 버전과 기능을 알려 주지만, 이것은 문을 여는 절차가 아니어서 클라이언트는 바로 tools/list를 보내도 됩니다. 성공한 결과에는 resultType이 붙고, 목록과 읽기 결과에는 캐시 힌트 ttlMs와 cacheScope가 붙습니다. 이 장의 실험에서는 요청에 결함을 하나씩 넣어 어느 검사 단계에서 어떤 오류 코드로 멈추는지 따라갑니다. 그런데 노트 비서가 노트 서버 하나가 아니라 여러 서버를 함께 쓰게 되면 어떻게 될까요?'],
 formula:'봉투 → _meta → 헤더·본문 일치 → 지원 버전 → 기능·메서드 → 인증·인가 → 핸들러',formulaNote:'원본 레슨 06이 정리한 검사 순서입니다. 앞 단계에서 실패하면 뒤 단계는 실행하지 않으므로, 한 요청에 결함이 둘이면 앞 단계의 오류만 보입니다. 헤더 검사와 인증은 Streamable HTTP에만 있고 stdio에서는 해당하지 않습니다. 실험의 HTTP 상태 코드는 원본 레슨과 MCP 2026-07-28 명세(기본 프로토콜, Streamable HTTP)가 밝힌 값입니다.',
 flow:['봉투|jsonrpc·id·method·params','_meta|버전과 기능이 있는가','헤더와 버전|본문과 같은가, 지원하는가','실행|기능·인가 확인 후 핸들러'],
 details:[
 ['오류 코드와 결과 모양','<div class="table-wrap"><table><tr><th>상황</th><th>JSON-RPC 오류</th><th>HTTP</th></tr><tr><td>_meta의 버전·기능이 없거나 형식이 틀림</td><td>-32602</td><td>400</td></tr><tr><td>헤더(MCP-Protocol-Version, Mcp-Method, Mcp-Name)와 본문 불일치</td><td>-32020</td><td>400</td></tr><tr><td>헤더와 본문이 같지만 지원하지 않는 버전</td><td>-32022, data에 supported·requested</td><td>400</td></tr><tr><td>필요한 클라이언트 기능 없음</td><td>-32021, data에 requiredCapabilities</td><td>400</td></tr><tr><td>모르는 메서드</td><td>-32601</td><td>404</td></tr><tr><td>id 없는 알림</td><td>응답 없음</td><td>202, 본문 없음</td></tr></table></div><p>도구가 실행되었지만 도구 자체가 실패하면 JSON-RPC 오류가 아니라 정상 결과에 <code>isError: true</code>를 담습니다. 버전 오류를 받은 클라이언트는 supported 가운데 함께 지원하는 버전을 골라 새 id로 다시 보냅니다.</p>'],
 ['서버를 만들 때 지키는 것','<ul><li><b>디스패치 고리</b>: 한 줄을 읽고, 봉투를 해석하고, 알림이면 답하지 않고, _meta를 검사하고, 메서드로 보내고, resultType과 serverInfo를 붙여 한 줄로 쓰고, 요청의 메타데이터를 잊습니다.</li><li><b>stdio 규칙</b>: stdout에는 JSON-RPC 메시지만, 진단은 stderr로, 메시지마다 줄바꿈과 flush, stdin이 닫히면 곧 종료합니다. 프로세스 수명은 전송 수명일 뿐 세션이 아닙니다.</li><li><b>결정적 목록</b>: 같은 요청에는 같은 순서의 목록을 돌려 캐시 키와 모델 문맥을 안정시킵니다. 안전한 기본 캐시 힌트는 <code>ttlMs: 0</code>, <code>cacheScope: "private"</code>입니다.</li><li><b>도구 주석은 힌트</b>: readOnlyHint, destructiveHint, idempotentHint, openWorldHint는 확인 화면에 쓰는 힌트일 뿐이고 실제 권한은 서버가 집행합니다.</li><li><b>서버는 먼저 요청하지 않음</b>: 샘플링이나 사용자 입력이 필요하면 독립 요청을 보내지 않고 input_required 결과를 돌려줍니다(6장).</li><li><b>옛 시대 호환</b>: 2025-11-25까지의 initialize 방식은 따로 분리된 호환 경로로만 둡니다.</li></ul>']],
 warning:'clientInfo와 serverInfo는 스스로 밝힌 이름일 뿐 신원 증명이 아닙니다. 또 “상태가 없다”는 말은 애플리케이션이 데이터를 저장하지 못한다는 뜻이 아니라, 프로토콜이 연결에 숨은 상태를 두지 않는다는 뜻입니다. 노트나 작업은 공유 저장소에 두고 명시적인 핸들로 가리키면 됩니다.',
 quiz:['HTTP로 온 요청의 MCP-Protocol-Version 헤더는 2026-07-28인데 본문 _meta의 버전은 2027-01-01입니다. 서버가 돌려줄 오류는?',['-32022 지원하지 않는 버전','-32020 헤더와 본문 불일치','-32601 모르는 메서드'],1,'원본의 순서는 헤더와 본문이 같은지 먼저 확인하고, 같다는 것이 확인된 뒤에야 버전 지원 여부를 봅니다. 한쪽 버전이 지원되지 않더라도 불일치가 먼저입니다.']},

{id:'client',title:'여러 서버를 묶고 전송을 고르기',subtitle:'클라이언트는 서버마다 장부를 두고 이름 충돌을 정책으로 풉니다. 원격 서버는 POST 한 곳만 엽니다.',desc:'두 서버가 모두 search라는 도구를 내놓으면 어느 쪽이 불릴까요?',group:'MCP 프로토콜',time:'17분',labs:['replica'],source:[9,10,36,35],thumb:['발견','이름공간','POST'],
 paragraphs:[
 '앞 장에서 노트 서버는 요청 한 통만 보고도 판단할 수 있게 되었습니다. 이제 노트 비서는 노트 서버와 이슈 서버, 그리고 예전에 만든 보관 서버까지 셋을 함께 씁니다. 클라이언트는 서버마다 전송 수단, 고른 버전, 발견한 기능, 도구 목록, 기다리는 요청 id를 적은 장부를 두지만, 원본은 이것이 클라이언트의 기록일 뿐 프로토콜 세션이 아니라고 강조합니다. stdio 서버에는 먼저 server/discover를 보내는데, 결과가 오면 최신 서버이고, -32020·-32021·-32022 같은 알려진 최신 오류가 와도 최신 서버이므로 initialize로 내려가지 않습니다. 명세는 그 밖의 오류나 시간 초과를 옛 서버의 신호로 보고 initialize로 내려가라고 하며, 내려가기를 특정 오류 코드 하나에 묶지 말라고 합니다. 원본 레슨 08은 여기에 더해, 시간 초과가 죽은 서버와 옛 서버를 구분하지 못한다며 운영자가 옛 방식 허용 목록에 넣어 둔 서버에만 initialize를 시도하는 더 엄격한 운영 정책을 권합니다. 도구 목록을 합칠 때 두 서버가 모두 search를 내놓으면 접두어를 붙이거나 거부하는 정책을 고르고, 조용히 덮어쓰는 일은 하지 않습니다.',
 '원격 서버는 Streamable HTTP로 엽니다. 2026-07-28에서는 /mcp 같은 엔드포인트 하나가 POST만 받고, GET과 DELETE에는 405를 돌려주며, Mcp-Session-Id와 Last-Event-ID는 무시합니다. 요청마다 MCP-Protocol-Version과 Mcp-Method 헤더를 붙이고, tools/call·resources/read·prompts/get에는 Mcp-Name도 붙여 게이트웨이가 본문을 열지 않고 길을 고르게 하되, 서버는 본문과 같은지 확인합니다. 세션이 없으니 요청은 어느 복제본에나 갈 수 있고, 그래서 초안 같은 애플리케이션 상태를 복제본 메모리에만 두면 다음 요청이 다른 복제본에 도착했을 때 찾지 못합니다. 이 장의 실험에서는 복제본 수와 상태 설계를 바꾸며 다음 요청이 초안을 찾을 확률을 계산합니다. 그렇다면 노트 비서가 모델에게 보여 줄 노트 내용 자체는 어떤 모양으로 주고받아야 할까요?'],
 formula:'메모리에만 둘 때 = 1/N · 고정 경로 = 1 − m·(1 − 1/N) · 핸들과 공유 저장소 = 1',formulaNote:'다음 요청이 초안을 찾을 확률입니다. N은 복제본 수이고, 부하 분산기가 다음 요청을 복제본에 고르게 보낸다고 가정했습니다. m은 고정 경로(sticky routing)가 재시작·배포·장애 조치로 다른 복제본에 옮겨지는 비율로, 이 책이 정한 교육용 가정값 2%입니다. 원본 레슨 09는 고정 경로가 증상을 가릴 뿐 재시작이나 장애 조치 때 다시 깨진다고 설명합니다.',
 flow:['발견|server/discover로 시대와 버전','합치기|정렬 후 충돌은 접두어나 거부','길 찾기|정규 이름에서 서버와 원래 이름으로','전송|stdio는 줄 단위, HTTP는 POST만'],
 details:[
 ['클라이언트가 옛 방식으로 내려가도 되는 경우','<ol><li>server/discover 결과가 오면 최신 서버로 확정하고 함께 지원하는 가장 높은 버전을 고릅니다.</li><li>-32022가 오면 data.supported에서 고른 버전으로 새 id를 써서 다시 보냅니다. -32020이나 -32021이면 요청을 고칩니다. 어느 쪽이든 initialize를 보내지 않습니다.</li><li>그 밖의 오류나 시간 초과는 명세상 옛 서버의 신호이므로, 두 시대를 모두 지원하는 클라이언트는 initialize로 내려갑니다. 명세는 이 판정을 -32601 같은 특정 코드 하나에 묶지 말라고 합니다. 원본 레슨은 이 신호가 죽은 서버나 과부하와 구분되지 않는다며, <code>allow_legacy=True</code>로 고정 설정한 서버에만 기한을 둔 initialize를 한 번 보내는 더 엄격한 운영 정책을 권합니다. 이것은 명세의 요구가 아니라 원본이 고른 닫힌 쪽 정책입니다.</li><li>initialize 결과가 같은 id, result 하나, 설정한 옛 버전, 객체인 capabilities, 이름과 버전이 있는 serverInfo를 모두 갖출 때만 옛 시대를 고르고, 그 뒤에 notifications/initialized를 보냅니다.</li><li>도구 목록은 정렬해서 합치고, 모델은 정규 이름을 보고, 나가는 tools/call은 그 서버가 밝힌 원래 이름을 씁니다.</li></ol>'],
 ['Streamable HTTP의 규칙','<ul><li>요청 하나는 POST 하나이고, 응답은 JSON 하나이거나 그 요청에 딸린 알림 뒤에 최종 응답이 오는 SSE 스트림입니다. 클라이언트는 <code>Accept: application/json, text/event-stream</code>을 보냅니다.</li><li>요청에 딸린 SSE가 최종 응답 전에 끊기면 그 요청은 잃은 것입니다. 이어 받기를 시도하지 않고, 안전한 경우에만 새 id로 다시 보냅니다. 스트림을 닫는 것이 그 요청의 취소입니다.</li><li>목록 변경 알림은 클라이언트가 POST로 여는 <code>subscriptions/listen</code>으로 받습니다. 첫 메시지는 승인 알림이고, 모든 알림의 _meta에 구독 id(그 요청의 id)가 붙습니다.</li><li>Origin 헤더가 있는데 허용하지 않은 값이면 403을 돌려 DNS 리바인딩을 막습니다. 접두어 비교가 아니라 정확한 일치로 봅니다. 로컬 서버는 127.0.0.1에만 묶습니다.</li><li>안전하지 않거나 ASCII가 아닌 Mcp-Name 값은 <code>=?base64?…?=</code> 형식으로 보내고, 서버는 풀어서 본문과 비교합니다.</li></ul>']],
 warning:'stdio 프로세스가 오래 살아 있다고 해서 그것이 세션은 아닙니다. 프로세스가 죽으면 진행 중인 요청을 잃으므로, 다시 띄우고, 발견과 목록을 새로 받고, 구독을 다시 열고, 안전한 요청만 새 id로 다시 보냅니다. 고정 경로로 복제본 문제를 덮으면 평소에는 멀쩡하다가 배포하는 날 깨집니다.',
 quiz:['두 시대를 모두 지원하는 클라이언트가 stdio 서버에 server/discover를 보냈더니 -32022(지원하지 않는 버전)가 data.supported와 함께 돌아왔습니다. 클라이언트가 할 일은?',['옛 서버로 보고 initialize를 보낸다','최신 서버이므로 data.supported에서 함께 지원하는 버전을 골라 새 id로 다시 보낸다','응답이 오류이므로 그 서버를 버린다'],1,'-32022는 알려진 최신 오류이므로 서버가 최신 시대라는 증거입니다. 명세는 이때 initialize로 내려가지 말고 supported 목록의 버전으로 다시 보내라고 합니다.'],
 cross:[['AI 개발 작업대 05 · 빌린 리눅스 상자에서 일하기','../aie-workbench/#remote','stdio 서버는 터미널 프로그램처럼 표준 입력과 출력으로 이야기합니다. 원격 상자에서 접속이 끊겨도 프로세스를 살려 두는 방법을 보고 오면, 프로세스 수명과 프로토콜 세션을 왜 구분하는지 손에 잡힙니다.']]},

{id:'context',title:'행동, 읽을거리, 틀을 나누기',subtitle:'도구는 행동을, 자원은 URI로 가리키는 내용을, 프롬프트는 사용자가 고르는 틀을 맡고, 결과마다 캐시 범위를 밝힙니다.',desc:'같은 notes://inbox가 사람마다 다른 내용을 돌려주면 캐시는 어떻게 해야 할까요?',group:'MCP 프로토콜',time:'18분',labs:['cache'],source:[11,15,29,38,39,41,62,63],thumb:['tools','resources','prompts'],
 paragraphs:[
 '앞 장에서 노트 비서는 여러 서버의 도구를 이름 충돌 없이 합쳤습니다. 이제 노트 서버가 내놓을 것을 종류별로 나눕니다. 원본 레슨 10은 누가 고르고 무엇을 기대하는지에서 출발하라고 합니다. notes://note-1 같은 노트는 URI로 가리키는 내용이므로 자원이고, 노트를 지우는 notes_delete는 상태를 바꾸므로 도구이며, 사용자가 메뉴에서 고르는 review_note는 프롬프트입니다. 자원 목록과 읽기, 프롬프트 목록은 모두 캐시할 수 있는 결과여서 ttlMs(얼마 동안 다시 써도 되는지)와 cacheScope(누구와 함께 써도 되는지)를 붙입니다. cacheScope 값은 public과 private 둘뿐이고, 사용자마다 다른 노트 내용에는 private를 씁니다. 모르는 URI를 읽으면 빈 결과가 아니라 -32602 오류를 돌려줍니다.',
 '도구 결과도 글 한 덩어리가 아닙니다. 원본 레슨 28에 따르면 content 배열에는 text, image, audio, resource_link, resource 다섯 종류가 섞일 수 있고, outputSchema를 밝힌 도구의 structuredContent는 그 스키마를 따라야 하며, 객체뿐 아니라 배열이나 문자열일 수도 있습니다. 목록은 커서로 나누어 받는데 빈 문자열도 올바른 커서이므로, nextCursor가 아예 없을 때만 멈춰야 합니다. 원본 레슨 14의 MCP Apps 확장은 도구 정의에 ui:// 자원을 미리 묶어 두고, 호스트가 그 HTML을 샌드박스 iframe에 띄워 화면을 보여 줍니다. 이 장의 실험에서는 지우와 민호가 같은 notes://inbox를 번갈아 읽을 때 cacheScope와 ttlMs를 바꾸며 캐시 적중, 다른 사람 노트의 누출, 낡은 내용이 몇 번 생기는지 셉니다. 그런데 서버가 일을 하다가 사용자에게 무언가를 물어야 한다면 어떻게 해야 할까요?'],
 formula:'캐시 키 = URI (public) 또는 URI + 요청자 (private) · 적중 ⇔ 같은 키 ∧ 경과 시간 < ttlMs',formulaNote:'실험은 같은 URI 하나를 여덟 번 읽는 미리 정한 시나리오이며, public 캐시는 요청자를 키에 넣지 않는다고 단순화했습니다. 원본은 공유 캐시 키에 테넌트, 사용자, 범위, 언어, 페이지 커서처럼 보이는 내용을 바꾸는 모든 차원을 넣으라고 하고, 그럴 수 없으면 private와 ttlMs 0에 호스트의 저장 금지 정책을 더하라고 합니다. no-store는 cacheScope 값이 아닙니다.',
 flow:['고르는 주체|모델·호스트·사용자','자원|안정된 URI와 MIME 형식','결과|content 다섯 종류와 structuredContent','캐시|ttlMs와 cacheScope'],
 details:[
 ['세 가지 기본 요소와 구독','<div class="table-wrap"><table><tr><th>요소</th><th>목적</th><th>고르는 주체</th><th>결과</th></tr><tr><td>도구</td><td>행동 수행</td><td>모델이나 애플리케이션</td><td>구조화된 행동 결과</td></tr><tr><td>자원</td><td>URI의 내용 읽기</td><td>호스트, 애플리케이션, 사용자</td><td>텍스트나 이진 내용</td></tr><tr><td>프롬프트</td><td>준비된 메시지 흐름 시작</td><td>호스트 화면을 쓰는 사용자</td><td>프롬프트 메시지</td></tr></table></div><ul><li>자원 URI는 이름공간을 갖고, 연결이나 프로세스와 무관하며, 읽을 때마다 권한을 확인합니다. 자원 템플릿(<code>notes://projects/{project}/…</code>)도 변수를 검사합니다.</li><li>자원 내용과 프롬프트 틀은 신뢰할 수 없는 서버 출력으로 다룹니다. prompts/get은 호스트의 시스템 지시를 대신하지 않습니다.</li><li>변경 알림은 <code>subscriptions/listen</code>의 notifications 허용 목록(resourcesListChanged, resourceSubscriptions 등)으로 받습니다. 알림은 바뀌었다는 사실만 알리고, 새 내용은 다시 resources/read로 권한을 거쳐 읽습니다.</li></ul>'],
 ['도구 계약의 세부 (레슨 28)','<ul><li>inputSchema와 outputSchema는 $schema가 없으면 2020-12 방언입니다. 인자가 없는 도구도 <code>{"type":"object","additionalProperties":false}</code>로 받는 것을 정확히 밝힙니다.</li><li>outputSchema를 밝힌 도구는 <code>isError: true</code>인 결과에서도 그 스키마를 지킵니다. 호환을 위해 같은 JSON을 text 블록에도 넣지만 검증 기준은 structuredContent입니다.</li><li>resource_link는 나중에 읽을 주소일 뿐이라 따라갈 때 다시 권한을 확인하고, 내장 resource에는 지금 크기 제한을 적용합니다.</li><li>입력 속성에 <code>x-mcp-header</code>를 달면 그 값을 <code>Mcp-Param-{이름}</code> 헤더로 복사해 게이트웨이가 길을 고르게 합니다. 스키마 루트에서 properties 키만 따라 닿는 속성(중첩 객체 속성 포함, 배열·조합·$ref 경로 제외)의 string·integer·boolean에만 쓰고, 비밀 값은 복사하지 않으며, 서버는 헤더와 본문이 다르면 400과 -32020으로 거절합니다.</li><li>completion/complete는 값을 최대 100개까지 제안하며, 참조하는 프롬프트나 자원과 같은 권한 경계를 적용합니다.</li></ul>'],
 ['MCP Apps 확장 (레슨 14)','<p>확장 이름은 <code>io.modelcontextprotocol/ui</code>이고 양쪽이 요청마다 기능으로 밝힙니다. tools/list의 도구 정의에 <code>_meta.ui.resourceUri</code>로 ui:// 자원을 미리 묶어, 호스트가 호출 전에 내려받고 검토할 수 있게 합니다. HTML 자원은 <code>text/html;profile=mcp-app</code>으로 오고, CSP 도메인 목록은 비워 둔 채 필요한 출처만 더합니다. iframe과 호스트 사이의 <code>ui/initialize</code>는 그 다리만의 인사이며 MCP 세션을 되살리지 않습니다. 확장을 밝히지 않은 호스트에는 같은 도구를 UI 없이 글 결과로 돌려줍니다.</p>']],
 warning:'cacheScope를 private로 두면 끝났다고 생각하기 쉽지만, 캐시 힌트는 권한 확인을 대신하지 않습니다. 또 private로 바꾸면 다른 사람 노트가 새는 일은 막아도, ttlMs가 길면 내가 방금 추가한 노트가 보이지 않는 낡은 내용 문제는 그대로 남습니다. 범위와 시간은 서로 다른 위험을 다룹니다.',
 quiz:['지우와 민호가 같은 notes://inbox를 읽는데 서버가 cacheScope: "public", ttlMs 30000을 붙였습니다. 지우가 읽고 10초 뒤 민호가 읽으면 무슨 일이 생길까요?',['민호는 자기 노트를 새로 받는다','공유 캐시가 지우의 응답을 민호에게 돌려주어 지우의 노트가 샌다','ttlMs 때문에 오류가 난다'],1,'public은 여러 사용자가 응답을 함께 써도 된다는 뜻입니다. 사용자마다 다른 내용에 public을 붙이면 공유 캐시가 남의 응답을 돌려줍니다.'],
 cross:[['검색과 RAG 09 · 근거를 얼마나 넣을까','../rag/#context','자원으로 읽은 노트는 결국 모델 입력의 근거가 됩니다. 토큰 예산 안에 근거를 얼마나 넣을지 따지는 장을 보면, 결과를 링크로 줄지 내장으로 줄지 고르는 기준이 분명해집니다.']]},

{id:'mrtr',title:'서버가 사람과 모델에게 되묻기',subtitle:'서버는 요청을 보내지 않고 input_required로 답합니다. 클라이언트는 원래 요청을 새 id로 다시 보내고, 서버는 서명된 상태로 맥락을 되찾습니다.',desc:'“오래된 TPS 보고서를 지워 줘”에 맞는 노트가 셋이면 어떻게 할까요?',group:'MCP 프로토콜',time:'18분',labs:['rebind'],source:[12,13,37,64],thumb:['input','retry','state'],
 paragraphs:[
 '앞 장에서 노트 서버는 도구·자원·프롬프트를 나누고 결과마다 캐시 범위를 밝혔습니다. 이제 사용자가 “오래된 TPS 보고서를 지워 줘”라고 말했는데 제목이 맞는 노트가 세 개라면, 서버는 어느 것인지 사용자에게 물어야 합니다. 예전 방식에서는 서버가 클라이언트에게 거꾸로 요청을 보냈지만, 2026-07-28에서는 서버가 독립 요청을 시작하지 않습니다. 대신 tools/call에 resultType이 input_required인 결과를 돌려주면서 inputRequests 안에 elicitation/create 양식(note_id 선택과 확인)을 넣고, 무결성이 보호된 requestState를 붙입니다. 클라이언트는 양식을 사용자에게 보여 준 뒤 원래 메서드와 인자를 그대로 새 JSON-RPC id로 다시 보내면서, inputResponses와 함께 requestState를 바이트 그대로 돌려줍니다. 이 방식이 MRTR(Multi Round-Trip Request)이며 tools/call, prompts/get, resources/read에서만 쓸 수 있습니다.',
 '사용자 응답에는 accept, decline, cancel 세 가지가 있고 서로 다르게 다룹니다. accept는 내용을 검사한 뒤 진행하고, decline은 오류가 아닌 완료된 거절로 끝내며, cancel은 아무것도 바꾸지 않고 나중에 다시 시도할 수 있게 둡니다. requestState는 클라이언트가 마음대로 바꿔 보낼 수 있으므로, 원본은 인증된 주체, 원래 메서드, 인자의 다이제스트, 보여 준 후보 목록, 짧은 만료를 묶어 서명하고, 지우기처럼 되돌릴 수 없는 일에는 한 번만 쓸 수 있는 nonce를 공유 저장소에 둡니다. 서버가 호스트의 모델을 빌려 쓰던 샘플링과 작업 폴더를 알려 주던 roots는 이번 판에서 폐기 예정이 되었고, 새 서버는 모델을 직접 부르고 범위는 도구 인자나 URI로 드러내는 쪽을 권합니다. 이 장의 실험에서는 다시 보낸 요청을 하나씩 변조해 어느 검사에서 멈추는지, 노트가 지워지는지 확인합니다. 그런데 사용자가 승인한 뒤에도 보고서 생성처럼 몇 분이 걸리는 일은 요청 하나에 담을 수 있을까요?'],
 formula:'지운다 ⇔ 서명 ∧ 만료 전 ∧ 같은 주체 ∧ 같은 인자 ∧ 올바른 accept ∧ 후보 안 ∧ nonce 처음',formulaNote:'원본 레슨 12의 지우기 확인을 이 실험의 검사 순서로 적었습니다. 서명·만료·주체·인자 묶음이 깨지면 -32602로 거절합니다. 응답 형식이 틀리거나 cancel이면 nonce를 쓰지 않아 만료 전까지 다시 시도할 수 있고, decline은 nonce를 소비하되 아무것도 지우지 않습니다. 실험은 서명을 실제로 계산하지 않고 각 검사의 통과 여부만 시나리오로 정합니다.',
 flow:['첫 호출|input_required와 서명된 requestState','사용자|양식에 accept·decline·cancel','재시도|같은 메서드와 인자, 새 id','검증|서명·주체·인자·후보·nonce'],
 details:[
 ['샘플링에서 MRTR로 (레슨 11)','<ul><li>새 서버의 기본은 모델 제공자를 직접 부르는 것입니다. 모델 선택, 자격 증명, 예산, 재시도, 관찰을 서버가 맡고 tools/call 결과 하나를 돌려줍니다.</li><li>호스트의 모델을 꼭 써야 하는 기존 흐름만 inputRequests 안에 <code>sampling/createMessage</code>를 넣는 호환 경로로 옮기고, 제거 계획을 기록합니다. 클라이언트가 sampling 기능을 밝히지 않으면 -32021입니다.</li><li>라운드마다 그 라운드의 응답만 오므로, 서버는 단계와 검증한 중간 값을 다음 requestState에 넣습니다. 클라이언트는 requestState를 해석하거나 고치지 않습니다.</li><li>modelPreferences의 costPriority·speedPriority·intelligencePriority는 서로 독립인 힌트이며 합이 1일 필요가 없고 클라이언트가 무시할 수도 있습니다. includeContext는 <code>"none"</code>으로 둡니다.</li><li>라운드 수, 라운드당 바이트와 토큰에 상한을 두고, 모델 출력을 파일 이름이나 URL로 쓰기 전에 검사합니다. 모델 출력은 권한 판단에 쓰지 않습니다.</li></ul>'],
 ['범위는 드러내고, 확인은 묶는다 (레슨 12)','<ul><li>roots는 처음부터 보안 샌드박스가 아니었습니다. 대신 <code>workspaceUri</code> 같은 도구 인자, 자원 URI, 서버 설정, 운영체제 샌드박스를 씁니다.</li><li>범위에는 세 층을 모두 적용합니다. 이 주체가 이 작업 공간을 써도 되는가(인가), 정규화한 경로가 그 안에 있는가(포함), 뚫린 서버를 운영체제가 막을 수 있는가(샌드박스).</li><li>문자열 접두어 비교는 <code>file:///work/notes-evil/…</code>이나 <code>%2e%2e</code> 경로 탐색을 통과시키므로, 정규화한 뒤 경로 구성 요소로 비교하고 지우기 직전에 다시 확인합니다.</li><li>양식(form) 모드는 평평한 원시 필드만 쓰고 비밀번호·API 키·결제 정보를 받지 않습니다. 그런 정보는 서버가 관리하는 웹 흐름으로 보내는 URL 모드를 쓰며, URL 모드의 accept는 사용자가 URL을 열기로 했다는 뜻일 뿐입니다.</li><li>클라이언트 기능은 요청마다 다시 봅니다. <code>elicitation: {}</code>는 양식 지원과 같고, URL만 밝히면 양식 요청에 -32021입니다.</li></ul>']],
 warning:'requestState에 서명만 하면 끝이라고 생각하기 쉽습니다. 서명은 위조를 막지만, 만료 전의 올바른 상태를 두 번 보내는 재사용은 막지 못합니다. 되돌릴 수 없는 일에는 모든 서버 인스턴스가 함께 보는 저장소에서 nonce를 한 번만 소비해야 하고, 그 소비와 지우기를 한 트랜잭션으로 묶는 것이 바람직합니다.',
 quiz:['사용자가 지우기 확인 양식을 그냥 닫았습니다(cancel). 서버가 할 일은?',['decline처럼 nonce를 소비하고 거절로 끝낸다','아무것도 지우지 않고 nonce도 소비하지 않아, 만료 전이면 다시 시도할 수 있게 둔다','응답 내용이 없으므로 동의로 보고 지운다'],1,'cancel은 사용자가 닫았거나 끝내지 못한 경우입니다. 원본은 cancel과 형식이 틀린 응답에서는 아무것도 바꾸지 않고 다시 시도할 수 있게 두며, 내용이 없는 것을 동의로 해석하지 말라고 합니다.']},

{id:'tasks',title:'오래 걸리는 일과 끊긴 연결',subtitle:'몇 분짜리 일은 작업 핸들로 돌려주고, 요청 취소와 작업 취소, 두 시계, 멱등 키를 구분합니다.',desc:'보고서 생성이 몇 분 걸리면 노트 비서는 무엇을 붙잡고 기다려야 할까요?',group:'MCP 프로토콜',time:'18분',labs:['tasklife','deadline'],source:[14,30,40,42],thumb:['task','poll','cancel'],
 paragraphs:[
 '앞 장에서 노트 비서는 사용자에게 되묻고 확인을 받아 일을 이어 갔습니다. 이번에는 사용자가 한 달치 회의 노트로 보고서를 만들어 달라고 합니다. generate_report는 몇 분이 걸릴 수 있으므로, 원본 레슨 13은 공식 Tasks 확장(io.modelcontextprotocol/tasks)을 씁니다. 클라이언트가 요청마다 확장 지원을 밝히면, 서버는 그 호출을 작업으로 만들지 스스로 정하고, 작업을 공유 저장소에 먼저 기록한 뒤에야 resultType이 task인 결과와 taskId, status, ttlMs, pollIntervalMs를 돌려줍니다. 클라이언트는 tasks/get으로 상태를 묻고, 작업이 사용자 입력을 기다리면 tasks/update로 답하고, 그만두고 싶으면 tasks/cancel을 보냅니다. tasks/get 자체는 언제나 resultType complete로 끝나므로, 조회가 끝났다는 뜻과 작업이 끝났다는 뜻을 status로 구분해 읽어야 합니다.',
 'tasks/cancel의 응답은 취소하겠다는 뜻을 받았다는 확인일 뿐 일이 멈췄다는 보장이 아닙니다. 작업은 취소가 전달되기 전에 끝날 수도 있으므로 클라이언트는 끝난 상태가 보일 때까지 계속 묻습니다. 원본 레슨 29는 여기에 요청 하나의 취소를 더합니다. stdio에서는 notifications/cancelled 알림을, HTTP에서는 그 요청의 응답 스트림을 닫는 것이 취소이고, 진행 알림은 유휴 시계를 늦출 수는 있어도 최대 시계를 없애지 못합니다. 응답을 잃어 다시 보낼 때 새 JSON-RPC id는 같은 일을 두 번 실행하게 하므로, 상태를 바꾸는 일에는 인자 지문과 함께 저장하는 멱등 키가 필요합니다. 이 장의 실험에서는 작업 이야기를 한 단계씩 진행해 resultType과 status가 어떻게 갈리는지 보고, 진행 알림 간격과 작업 길이를 바꾸며 두 시계 중 무엇이 먼저 울리는지 계산합니다. 그런데 노트 서버가 쓰는 도구 설명 자체를 누군가 몰래 바꾼다면 노트 비서는 알아챌 수 있을까요?'],
 formula:'마감 = min(마지막 진행 + 유휴 제한, 최대 제한) · 진행이 와도 최대 제한은 그대로',formulaNote:'유휴 제한 500ms, 최대 제한 2000ms, 400ms마다 오는 진행 알림은 원본 레슨 29의 예입니다. 작업 길이와 진행 간격은 슬라이더로 바꾸며, 진행 알림은 정확히 간격마다 온다고 가정했습니다. 원본 예처럼 400ms 간격이면 1500ms에도 살아 있지만 2000ms에는 최대 제한으로 취소됩니다.',
 flow:['생성|기록한 뒤 resultType task','조회|tasks/get은 complete, status는 따로','입력|input_required면 tasks/update','종료|completed·cancelled·failed'],
 details:[
 ['작업 모양과 실패의 두 층 (레슨 13)','<ul><li><b>작업 필드</b>: taskId, status(working·input_required·completed·cancelled·failed), createdAt·lastUpdatedAt, 생성 시점부터 재는 ttlMs, 서버가 바꿀 수 있는 pollIntervalMs, statusMessage.</li><li><b>끝난 작업</b>: completed면 원래 CallToolResult가 <code>result</code>에 들어오고 그 안에도 resultType이 있습니다. tasks/result와 tasks/list는 없습니다.</li><li><b>입력</b>: 작업을 만들기 전에 입력이 필요하면 6장의 MRTR을 쓰고, 만든 뒤에 필요하면 status를 input_required로 바꾸고 tasks/update로 받습니다. inputRequests 키는 작업 전체에서 유일해야 합니다.</li><li><b>실패</b>: 도구가 <code>isError: true</code>로 끝나도 작업은 completed입니다. 미뤄진 실행에서 JSON-RPC 오류가 나면 failed이고 error를 담습니다. 확장을 밝히지 않은 클라이언트에는 -32021입니다.</li><li><b>소유</b>: taskId를 안다고 접근할 수 있으면 안 됩니다. tasks/get·update·cancel마다 테넌트와 주체를 확인하고, HTTP에서는 Mcp-Name에 taskId를 넣습니다.</li></ul>'],
 ['취소·재시도·흐름 제어 (레슨 29)','<div class="table-wrap"><table><tr><th>장치</th><th>대상</th><th>신호</th><th>성공의 뜻</th></tr><tr><td>stdio 요청 취소</td><td>진행 중인 RPC 하나</td><td>notifications/cancelled</td><td>클라이언트가 포기, 서버는 가능하면 멈춤</td></tr><tr><td>HTTP 요청 취소</td><td>응답 스트림 하나</td><td>스트림 닫기</td><td>같음</td></tr><tr><td>tasks/cancel</td><td>지속 작업 하나</td><td>일반 MCP 요청</td><td>취소 의사를 받았다는 확인</td></tr></table></div><ul><li>취소가 먼저면 서버는 최종 응답을 보내지 않고, 완료가 먼저면 늦게 온 취소를 무시합니다.</li><li>재시도는 셋으로 나눕니다. 부작용 없는 읽기는 새 id로, 멱등 키가 있는 변경은 같은 키와 같은 인자로, 키 없는 변경은 자동으로 다시 보내지 않고 대조부터 합니다. 같은 키에 다른 인자가 오면 거부합니다.</li><li>진행 알림 큐에는 상한을 두고, 진행은 합치거나 오래된 것부터 버리되 최종 응답은 버리지 않습니다. SSE 응답에는 <code>X-Accel-Buffering: no</code>를 보냅니다.</li><li>재연결은 이어 받기가 아니라 새 요청과 다시 읽기이며, 원본 예는 250ms에서 두 배씩 늘려 8000ms에서 멈추는 지터 백오프를 씁니다.</li></ul>']],
 warning:'tasks/cancel이 성공했다고 화면에 “취소됨”을 띄우면 안 됩니다. 확인 응답은 의사를 받았다는 뜻일 뿐이고, 작업은 그 뒤에도 working이거나 이미 completed일 수 있습니다. 마찬가지로 요청의 HTTP 스트림을 닫아도 이미 task 결과를 돌려준 지속 작업은 멈추지 않습니다.',
 quiz:['tasks/get 응답이 resultType: "complete", status: "working"입니다. 바른 해석은?',['보고서 생성이 끝났으므로 결과를 읽는다','tasks/get 호출은 끝났고 보고서 작업은 아직 진행 중이므로 pollIntervalMs를 지켜 다시 묻는다','오류이므로 tools/call을 다시 보낸다'],1,'바깥 resultType은 조회 RPC가 끝났다는 뜻이고, status가 작업 자체의 상태입니다. 둘을 섞는 것이 원본이 경고한 흔한 해석 버그입니다.'],
 cross:[['추론 최적화 01 · 느리다는 말을 숫자로 바꾸기','../llm-performance/#metrics','유휴 시계와 최대 시계는 결국 “얼마나 기다릴 것인가”를 숫자로 정하는 일입니다. 첫 토큰 대기와 전체 시간을 따로 재는 장을 보면 진행 알림과 최종 응답을 왜 다르게 다루는지 연결됩니다.']]},

{id:'poison',title:'도구 설명과 공급망을 믿지 않기',subtitle:'설명은 모델이 읽는 입력입니다. 승인한 서술자 전체를 고정하고, 레지스트리에 있다는 사실과 우리가 승인했다는 사실을 나눕니다.',desc:'어제 승인한 export 도구의 서술자가 오늘 바뀌었다면?',group:'보안과 운영',time:'18분',labs:['admit'],source:[16,31,48,33],thumb:['스캔','고정','격리'],
 paragraphs:[
 '앞 장까지 노트 비서는 오래 걸리는 일까지 안정적으로 다루게 되었습니다. 그런데 모델은 도구를 고를 때 설명을 그대로 읽으므로, 설명 하나가 모델과 라우터와 사용자를 함께 속일 수 있습니다. 원본 레슨 15는 점검할 공격 면을 일곱 가지로 꼽습니다. 설명에 엉뚱한 지시를 숨기는 메타데이터 중독, 승인한 뒤 이름·설명·스키마가 바뀌는 러그 풀, 두 서버가 같은 이름을 내놓는 그림자, 헤더와 본문의 불일치, 기능 선언을 권한으로 착각하는 일, requestState 변조, 낯익은 표시 이름을 신원으로 믿는 공급망 혼동입니다. 대응도 겹겹이 쌓습니다. 승인한 서술자 전체를 키 순서를 정렬한 JSON으로 만들어 해시로 고정하고, 새로 고칠 때마다 비교하며, 간단한 패턴 검사를 덫으로 두고, 공개 이름에는 notes.export처럼 서버 이름공간을 붙입니다.',
 '해시가 같다는 것은 내용이 그대로라는 뜻이지 안전하다는 뜻이 아닙니다. 처음 승인한 설명이 이미 중독되어 있었다면 완벽하게 고정된 중독일 뿐이고, 패턴 검사는 경고 문장 속의 낱말에도 걸리는 반면 교묘한 지시는 놓칩니다. 원본 레슨 30은 같은 생각을 공급망으로 넓힙니다. 레지스트리에 이름이 있다는 것은 그 이름공간을 인증받은 게시자가 기록을 올렸다는 뜻일 뿐이므로, 이름공간을 정확히 비교하고, 기록·패키지·실제 도구 목록의 다이제스트를 따로 고정하고, 레지스트리 상태가 deprecated나 deleted로 바뀌면 격리하며, 되돌리기는 예전에 승인한 버전으로 경로만 돌리는 일로 다룹니다. 이 장의 실험에서는 노트 서버의 export 서술자를 여러 방식으로 바꾸며 다이제스트, 스캐너 경고, 심사 결정이 어떻게 달라지는지 봅니다. 그렇다면 서술자를 믿을 수 있게 된 다음, 그 도구를 부르는 사람이 누구인지는 어떻게 확인할까요?'],
 formula:'처음 보는 이름 → 격리 · 스캐너 경고 → 검토 · 다이제스트 ≠ 고정값 → 격리 · 이름 충돌 → 이름공간 · 그 밖 → 허용',formulaNote:'원본 레슨 15의 새로 고침 규칙을 이 실험의 판정 순서로 적었습니다. 원본은 정렬된 JSON에 SHA-256을 쓰지만, 이 실험은 화면에 짧게 보이도록 같은 정렬 JSON에 32비트 FNV-1a를 씁니다. 해시 계산은 실제이고 서술자 변형은 미리 정한 시나리오입니다. 32비트 해시는 충돌을 만들기 쉬우므로 실제 고정에는 쓰면 안 됩니다.',
 flow:['정규화|키를 정렬한 JSON','고정|승인한 다이제스트 저장','비교|새로 고칠 때마다 다시 계산','결정|허용·검토·격리·이름공간'],
 details:[
 ['요청의 증거와 권한을 줄이는 순서 (레슨 15)','<ul><li>헤더의 Mcp-Method·Mcp-Name이 본문과 다르면 백엔드를 고르거나 권한을 보거나 속도 제한 토큰을 쓰기 전에 -32020으로 거절합니다. 한 구성 요소가 본문으로 허가하고 다른 구성 요소가 헤더로 길을 고르는 틈을 닫습니다.</li><li>clientCapabilities는 호환성 선언일 뿐 권한이 아닙니다. 순서는 전송 인증, 버전·헤더·모양 검사, 기능 호환, 주체·도구·자원·인자 인가, 실행 또는 입력 요청입니다.</li><li>세 가지 위험(신뢰할 수 없는 입력, 민감한 데이터, 결과가 남는 행동)을 한 자동 단계에 모두 묶지 않습니다(둘의 규칙). 원본은 이것을 프로토콜 기능이 아닌 설계 원칙으로 소개합니다.</li><li>권한은 단계마다 줄입니다. 좁은 동사의 도구, 닫힌 스키마로 검사한 인자, 지금의 인가, 동작과 인자 다이제스트에 묶인 승인, 정상 결과로서의 거절, 비밀을 지운 감사 기록.</li><li>세션이 없으므로 승인·속도 제한·감사를 Mcp-Session-Id에 묶지 않고 인증된 주체, 발급자, 자원, 도구, 시간 창에 묶습니다.</li></ul>'],
 ['레지스트리 공급망 (레슨 30)','<ul><li><b>이름공간</b>: <code>startswith("com.example")</code>는 <code>com.exampleevil/tool</code>도 통과시킵니다. / 앞의 이름공간을 정확히 비교하고, 신뢰는 기록 안의 글이 아니라 인증 결과에서 받습니다.</li><li><b>출처 결합</b>: 패키지 종류·식별자·버전·소유 확인 결과·내려받은 산출물 다이제스트를 묶습니다. 원격 엔드포인트만 있는 기록도 올바른 기록입니다.</li><li><b>고정</b>: 레지스트리 버전은 유일하고 게시된 메타데이터는 바뀌지 않습니다. <code>^1.4</code>나 latest는 고정이 아니며, 기록·실행 출처·도구 목록·출처 증거의 다이제스트를 함께 고정합니다.</li><li><b>상태</b>: 응답의 <code>_meta["io.modelcontextprotocol.registry/official"].status</code>가 active·deprecated·deleted 중 무엇인지 계속 맞춥니다. 게시자가 넣은 메타데이터는 공식 상태를 흉내 낼 수 없습니다. serverInfo는 진단 정보일 뿐 승인 근거가 아닙니다.</li><li><b>되돌리기와 장부</b>: 되돌리기는 승인 기록이 있고 상태가 active이며 격리되지 않은 버전으로 경로를 돌리는 일입니다. 결정마다 앞 항목의 해시를 담은 장부를 남겨 변조를 드러내고, 장부 머리는 다른 신뢰 영역에 서명해 둡니다.</li></ul>']],
 warning:'스캐너가 아무것도 찾지 못했다고 안전한 설명은 아니고, 스캐너가 경고했다고 반드시 악성인 것도 아닙니다. 노트 안의 “이전 지시를 무시하라”는 문장을 따르지 않는다고 정직하게 적은 설명도 같은 패턴에 걸립니다. 스캐너 결과는 사람이 서술자 전체를 검토할 근거이지 판결이 아닙니다.',
 quiz:['export 도구의 설명은 그대로인데 inputSchema에 recipient 필드가 하나 늘었습니다. 설명만 해시로 고정해 둔 게이트웨이는?',['설명이 같으므로 변화를 알아채지 못한다','스키마 변화도 반드시 잡아낸다','도구 이름이 바뀐 것으로 본다'],0,'원본은 설명만 해시하면 스키마와 주석 변화를 놓친다고 경고합니다. 승인한 서술자 전체를 정규화해 해시해야 이런 러그 풀을 잡습니다.'],
 cross:[['컴퓨터 원리 02 · 같은 비트, 다른 뜻','../computer/#encoding','같은 서술자도 키 순서나 공백이 다르면 바이트가 달라져 해시가 바뀝니다. 비트에는 이름표가 없다는 장을 보고 오면, 왜 정해진 규칙으로 먼저 정규화한 뒤 해시해야 하는지 납득됩니다.']]},

{id:'auth',title:'토큰은 누구를 위해 발급되었나',subtitle:'원격 MCP 서버는 요청마다 토큰의 발급자, 대상, 만료, 범위를 확인하고, 모르는 키는 새로 만들지 않고 한 번만 다시 받습니다.',desc:'노트 서버의 토큰을 할 일 서버에 내밀면 어떻게 될까요?',group:'보안과 운영',time:'18분',labs:['token'],source:[17,19,43,44,45,46,47,61],thumb:['PRM','PKCE','aud'],
 paragraphs:[
 '앞 장에서 노트 비서는 도구 서술자를 고정해 서버가 몰래 바뀌는 것을 막았습니다. 이제 원격 노트 서버는 그 도구를 누가 부르는지 확인해야 합니다. MCP 인가 명세는 HTTP 전송에만 적용되며, stdio 서버는 프로세스와 운영체제의 신뢰 경계 안에 있습니다. 클라이언트는 MCP 서버 URL에서 출발해 RFC 9728 보호 자원 메타데이터를 받아 믿을 인가 서버를 찾고, 그 서버의 메타데이터에서 PKCE의 S256 지원을 확인합니다. 클라이언트 등록은 미리 등록한 정보가 있으면 그것을, 없으면 HTTPS URL 자체가 클라이언트 id인 CIMD(Client ID Metadata Document)를 먼저 쓰고, 동적 등록(DCR)은 이번 판에서 폐기 예정인 호환 경로로만 둡니다. 인가 코드를 받으면 응답의 iss가 기록해 둔 발급자와 정확히 같은지 RFC 9207대로 확인한 뒤에야 코드를 교환하고, 토큰은 (발급자, 자원) 쌍으로 저장합니다.',
 '자원 서버 쪽에서는 매 요청마다 같은 검사를 돌립니다. 토큰의 kid로 캐시한 JWKS에서 서명 키를 찾고, 없으면 딱 한 번만 다시 받고, 서명을 확인한 뒤, iss가 허용 목록에 있는지, aud가 바로 이 MCP 서버의 정규 URI인지, 만료되지 않았는지, 이 도구에 필요한 범위가 있는지를 봅니다. aud가 없거나 다르면 401이고, 원본 레슨 18은 이것이 한 서버의 토큰을 같은 신뢰망의 다른 서버에 다시 내미는 공격을 막는 프로토콜 수준의 유일한 방어라고 말합니다. 범위가 모자라면 403과 함께 필요한 scope를 알리고, 클라이언트는 사용자 동의를 다시 받아 새 토큰으로 새 id를 써서 재시도합니다. 이 장의 실험에서는 토큰의 주장을 하나씩 망가뜨리며 어느 검사에서 어떤 상태로 멈추는지, JWKS를 몇 번 다시 받는지 계산합니다. 그런데 노트 서버, 이슈 서버, 할 일 서버가 늘어나면 이 검사와 정책을 서버마다 따로 둬야 할까요?'],
 formula:'200 ⇔ kid 찾음(최대 1회 재조회) ∧ 서명 ∧ iss ∈ 허용 목록 ∧ aud = 이 서버 ∧ 만료 전 ∧ 필요한 scope',formulaNote:'원본 레슨 18의 validate 순서입니다. 처음 실패한 검사에서 멈추며, scope 부족만 403(insufficient_scope)이고 나머지는 401(invalid_token)입니다. 실험의 토큰은 미리 정한 주장 묶음이며 서명은 계산하지 않습니다. 캐시에 있는 키 k_old·k_cur와 새로 게시된 키 k_new는 키 교체의 겹침 구간을 흉내 낸 시나리오입니다.',
 flow:['발견|PRM에서 인가 서버, 메타데이터에서 S256','등록|사전 등록, CIMD, DCR 순서','교환|iss 확인 후 code·verifier·resource','검증|kid·서명·iss·aud·exp·scope'],
 details:[
 ['클라이언트 쪽 규칙 (레슨 16)','<ul><li><b>메타데이터 위치</b>: 경로가 있는 자원은 경로 앞에 well-known을 끼웁니다. <code>https://notes.example.com/mcp</code>라면 <code>https://notes.example.com/.well-known/oauth-protected-resource/mcp</code>입니다.</li><li><b>PKCE</b>: 인가 서버 메타데이터에 S256이 없으면 진행하지 않습니다. 원본은 PKCE에 낮춘 모드가 없다고 말합니다.</li><li><b>CIMD</b>: 문서 안의 client_id는 문서 URL과 정확히 같아야 하고, client_id·client_name·redirect_uris가 필수입니다. 인가 서버는 이 URL을 가져오므로 SSRF를 막아야 합니다.</li><li><b>DCR 호환</b>: 쓸 때는 application_type을 밝힙니다. 데스크톱·모바일·명령줄·루프백 클라이언트는 native, 원격 웹 앱은 web입니다.</li><li><b>발급자별 격리</b>: 발급자가 바뀌면 이전 발급자의 client_id, 등록 토큰, 갱신 토큰, 접근 토큰을 새 발급자에게 보내지 않습니다. 스스로 호스팅하는 CIMD URL만은 그대로 쓸 수 있습니다.</li><li><b>mix-up 방어</b>: iss 확인은 클라이언트만 할 수 있습니다. PKCE만으로는 막지 못합니다.</li><li><b>토큰 전달 금지</b>: MCP 서버는 받은 토큰을 하류 API에 그대로 넘기지 않고 따로 토큰을 얻습니다.</li></ul>'],
 ['자원 서버의 운영 규칙 (레슨 18)','<ul><li><b>돌리기와 다시 받기</b>: 키를 돌리는(rotate) 것은 인가 서버의 일이고, 자원 서버는 JWKS를 다시 받는(refresh) 일만 합니다. 캐시에 없는 kid에 키를 새로 만들면 여전히 맞지 않고, 무작위 kid를 뿌리는 공격자가 키 생성을 끝없이 일으킵니다.</li><li><b>정기 갱신</b>: 일정 간격으로 JWKS를 받아 캐시를 덮어쓰고, 두 키가 겹치는 기간에는 둘 다 받아들입니다.</li><li><b>불투명 토큰</b>: JWT가 아니면 RFC 7662 내부 조회(introspection)로 active, 대상, 만료, 범위를 확인합니다. 캐시는 토큰 다이제스트와 자원으로 키를 잡고, 망 장애를 active로 바꾸지 않습니다.</li><li><b>폐기</b>: 폐기 요청이 모든 캐시를 지우지는 않으므로, 최대 지연을 정하고 그 안에 모든 복제본이 거절하게 합니다.</li><li><b>장애 정책</b>: 모르는 kid에 한 번의 재조회도 실패하면 거절합니다. 시계 오차를 넓혀 통과시키지 않습니다.</li></ul>']],
 warning:'같은 인가 서버가 발급한 토큰이면 어느 서버에서나 통한다고 생각하기 쉽습니다. 노트 서버용 토큰은 iss 검사를 통과해도 aud가 다르므로 할 일 서버에서는 401이어야 합니다. aud가 없는 토큰을 “모든 서버용”으로 받아 주어서도 안 됩니다.',
 quiz:['토큰의 kid가 자원 서버의 캐시에 없습니다. 자원 서버가 할 일은?',['새 서명 키를 만들어(rotate) 다시 검증한다','JWKS를 한 번 다시 받아 보고, 그래도 없으면 401로 거절한다','kid를 무시하고 서명 검사를 건너뛴다'],1,'캐시에 없는 kid에는 한 번의 다시 받기만 허용합니다. 키를 새로 만들면 맞는 kid가 생기지도 않고, 공격자가 키 생성을 강요할 수 있습니다.'],
 cross:[['AI 개발 작업대 07 · API 키를 코드 밖에 두기','../aie-workbench/#keys','토큰도 키처럼 URL이나 로그에 남으면 끝입니다. 키를 환경 변수에 두고 노출되면 폐기하는 습관을 먼저 보고 오면, 토큰을 Authorization 헤더에만 싣고 감사 기록에서 지우는 이유가 이어집니다.']]},

{id:'gateway',title:'한 문 뒤의 서버들을 관찰하고 고르기',subtitle:'게이트웨이는 요청마다 정책을 다시 계산하고, 트레이스는 모든 홉을 한 줄로 잇고, 라우터는 모델을 갈아 끼우며, 적합성 시험은 바이트로 증명합니다.',desc:'노트 비서가 어떤 때는 3초, 어떤 때는 30초 걸린다면 어디를 봐야 할까요?',group:'보안과 운영',time:'20분',labs:['trace'],source:[18,20,21,22,32,50,51,52,49],thumb:['gateway','span','route'],
 paragraphs:[
 '앞 장에서 노트 서버는 요청마다 토큰을 검증하게 되었습니다. 서버가 여럿이 되면 노트 비서는 게이트웨이 하나만 바라보고, 게이트웨이가 인증, 헤더와 _meta 검사, 인가, 서술자·레지스트리·속도 정책, 새 백엔드 요청 만들기, 결과 검사, 감사를 차례로 맡습니다. 원본 레슨 17은 레지스트리 승인이 어느 버전을 들여보낼지 정할 뿐 살아 있는 호출을 허가하지 않으므로, 게이트웨이가 요청마다 주체, 인자, 고정된 서술자, 백엔드 상태로 정책을 다시 계산해야 한다고 말합니다. 바깥 토큰은 백엔드에 넘기지 않고, 공개 이름 notes.search와 백엔드 이름의 대응을 따로 적고, 사용자마다 보이는 도구가 다르면 tools/list를 private로 캐시합니다. 다른 조직의 에이전트에게 일을 통째로 맡길 때는 MCP가 아니라 A2A를 씁니다. A2A에서 부르는 쪽은 Agent Card와 작업 상태, 산출물만 보고 상대 에이전트의 내부 추론은 보지 못합니다.',
 '어느 날 사용자가 노트 비서가 어떤 때는 3초, 어떤 때는 30초 걸린다고 알려 옵니다. 원본 레슨 20의 사례처럼 로그에 모델 호출만 보이고 도구 호출과 MCP 왕복은 보이지 않으면 짐작밖에 할 수 없습니다. OpenTelemetry GenAI 규약은 에이전트, 모델 호출, 도구 실행, MCP 호출을 한 트레이스의 부모-자식 스팬으로 묶고, 클라이언트가 traceparent를 MCP 요청에 실어 보내야 서버 쪽 스팬이 같은 트레이스에 들어갑니다. 모델 쪽 장애와 비용은 LiteLLM 같은 라우팅 게이트웨이의 별칭과 대체 사슬로 다루고, 게이트웨이 전체가 규칙을 지키는지는 정상 사례와 거절 사례의 선 위 기록으로 증명합니다. 이 장의 실험에서는 MCP 서버가 따뜻할 때와 콜드 스타트일 때, trace 문맥을 전파할 때와 하지 않을 때 폭포 그림이 어떻게 달라지는지 봅니다. 그렇다면 노트 비서가 매번 같은 순서로 하는 일을 절차로 묶어 둘 수는 없을까요?'],
 formula:'전체 = Σ 최상위 스팬 · 설명되지 않는 시간 = 전파가 끊긴 하위 스팬의 시간',formulaNote:'스팬 길이는 원본 레슨 20의 “3초와 30초” 사례를 흉내 낸 교육용 가정값입니다. 따뜻한 MCP 서버 300ms, 콜드 스타트 27,000ms, 모델 호출 1,200ms와 1,400ms, 도구 자체 처리 40ms로 두었습니다. 전파를 끄면 MCP 서버 스팬이 다른 트레이스에 생기므로, 도구 스팬이 길다는 사실만 보이고 그 안을 설명하지 못합니다.',
 flow:['게이트웨이|인증·검사·인가·정책·전달·감사','A2A|일을 통째로 맡기는 에이전트 사이 약속','트레이스|에이전트·모델·도구·MCP 스팬','적합성|정상·거절 기록과 되돌리기 증거'],
 details:[
 ['게이트웨이가 요청마다 하는 일 (레슨 17)','<ol><li>전송 인가에서 주체를 인증합니다.</li><li>MCP-Protocol-Version, Mcp-Method, Mcp-Name, params._meta를 검사하고, 불일치는 백엔드를 찾기 전에 -32020으로 거절합니다.</li><li>주체, 자원, 메서드, 도구, 인자를 인가합니다.</li><li>서술자 고정, 레지스트리, 속도, 데이터 정책을 적용합니다. 속도 제한은 세션이 아니라 주체, 발급자, 자원, 공개 도구, 비용 등급, 시간 창으로 잡습니다.</li><li>선택한 백엔드에 새 _meta를 담은 새 요청을 만듭니다. 바깥 클라이언트 기능을 그대로 복사하지 않고, 게이트웨이가 끝까지 지킬 수 있는 기능만 밝힙니다.</li><li>백엔드 결과를 검사해 돌려주고, 비밀을 지운 감사 기록을 남깁니다.</li></ol><p>MRTR의 requestState는 바이트 그대로 넘기고 재시도마다 다시 인가합니다. Tasks는 taskId별로 주체와 백엔드 경로를 기록해 tasks/get을 같은 백엔드로 보냅니다.</p>'],
 ['A2A, 트레이스, 라우팅 (레슨 19~21)','<ul><li><b>A2A</b>: 2025년 4월 Google이 발표하고 2025년 6월 Linux Foundation에 기증되었으며, 1.0.0은 2026년 3월(공식 저장소 릴리스 2026-03-12), 원본이 따르는 1.0.1은 2026년 5월에 나왔습니다. <code>/.well-known/agent-card.json</code>의 Agent Card에 스킬과 supportedInterfaces(JSONRPC, GRPC, HTTP+JSON)를 싣고, 작업은 SUBMITTED와 WORKING, 필요하면 INPUT_REQUIRED나 AUTH_REQUIRED를 거쳐 COMPLETED·FAILED·CANCELED·REJECTED로 끝납니다. 메시지 부분은 text·raw·url·data 중 하나를 담고, 결과는 산출물(Artifact)로 돌아옵니다. 요청마다 <code>A2A-Version: 1.0</code> 헤더를 보냅니다.</li><li><b>OTel GenAI</b>: 모델 스팬에서 gen_ai.operation.name과 gen_ai.provider.name은 필수, gen_ai.request.model은 알 수 있으면 필수(조건부)이고, gen_ai.response.model, 입력·출력 토큰 사용량, gen_ai.response.id는 권장 속성입니다(원본은 이들을 모두 필수로 묶어 소개합니다). 도구 스팬에는 gen_ai.tool.name과 gen_ai.tool.call.id를 답니다. 프로세스 경계를 넘는 모델·MCP 호출은 CLIENT, 에이전트 자신의 단계는 INTERNAL 스팬입니다. 프롬프트와 응답 내용은 기본으로 담지 않습니다.</li><li><b>라우팅</b>: OpenAI 형식의 API 하나로 별칭을 실제 모델에 대응시키고, 5xx면 다음 제공자로 넘어가는 대체 사슬, 요청별 비용 집계, 팀별 예산, 개인정보 가리기를 둡니다. 원본은 LiteLLM(직접 운영), OpenRouter(관리형), Portkey(운영 등급)를 비교합니다.</li></ul>'],
 ['적합성 시험과 출시 (레슨 31)','<ul><li>정상 기록과 거절 기록을 둘 다 둡니다. 거절 기록은 “실패했다”가 아니라 거절한 경계와 오류 코드를 확인하며, 헤더 불일치 사례는 서버의 실제 HTTP 400과 -32020 응답까지 확인해야 합니다.</li><li>최신 시대와 옛 시대를 한 검사기로 섞지 않습니다. 알려진 최신 오류(-32020, -32021, -32022) 뒤에는 옛 방식으로 내려가지 않습니다.</li><li>결과에 더해진 모르는 필드는 보존하거나 무시할 수 있지만, 모르는 resultType은 거부합니다.</li><li>SDK가 정리한 값과 선 위의 원본을 비교하고, 프록시가 원래의 400을 500으로 뭉개지 않았는지 들어온 곳·원 서버·나간 곳 세 지점을 봅니다.</li><li>증거는 해시하기 전에 Authorization, token, secret 같은 키의 값을 지웁니다. 출시는 건강 창과, 서명된 되돌리기 대상이 준비되어야 승인됩니다.</li></ul>']],
 warning:'traceparent를 전파하지 않으면 MCP 서버의 스팬은 따로 떨어진 트레이스로 남고, 노트 비서 쪽에서는 도구 스팬이 길다는 사실만 보입니다. 같은 트레이스 id가 보인다고 해서 부모 관계와 수집이 맞게 이어졌다는 증거도 아닙니다. 원본은 stdio처럼 HTTP 헤더가 없는 전송에서는 요청의 _meta에 traceparent를 직접 담으라고 권합니다.',
 quiz:['게이트웨이가 바깥 클라이언트에게 받은 Bearer 토큰을 노트 서버 백엔드에 그대로 넘기고 있습니다. 원본의 판단은?',['토큰을 한 번만 검증하면 되므로 효율적이다','바깥 토큰은 게이트웨이용이므로, 백엔드에는 그 발급자와 자원에 맞는 별도 자격 증명을 쓴다','A2A로 바꾸면 해결된다'],1,'게이트웨이는 호출자를 인증하고 백엔드에는 따로 인증합니다. 바깥 토큰을 넘기면 대상 검증이 무너지고 토큰 전달 금지 규칙을 어깁니다.'],
 cross:[['추론 최적화 07 · 병목 주장에 근거 붙이기','../llm-performance/#evidence','“MCP 서버가 느리다”는 말도 같은 구간의 시간을 맞춰 본 증거가 있어야 주장이 됩니다. 병목 주장에 측정을 붙이는 장을 보고 오면 폭포 그림에서 다음에 무엇을 잴지 정하기 쉬워집니다.']]},

{id:'skills',title:'절차를 스킬로 포장하기',subtitle:'스킬은 SKILL.md를 입구로 하는 꾸러미입니다. 목록에는 짧게, 본문은 고른 뒤에, 참고 파일은 필요할 때만 올리고, 라우팅은 근접 오답으로 평가합니다.',desc:'설치한 스킬이 200개면 모두 문맥에 넣어야 할까요?',group:'스킬과 종합',time:'20분',labs:['disclosure','routeval'],source:[23,25,26,27,28,53,54],thumb:['목록','본문','평가'],
 paragraphs:[
 '앞 장에서 노트 비서의 호출은 게이트웨이와 트레이스로 관찰할 수 있게 되었습니다. 이제 노트 비서가 매주 하는 출시 점검처럼 여러 단계를 같은 순서로 판단하는 일을 스킬로 포장합니다. 원본 레슨 22에 따르면 스킬은 YAML 머리말(name, description)과 Markdown 지시로 된 SKILL.md를 입구로 하고 references, scripts, assets를 함께 담은 디렉터리이며, 배포 단위는 파일 하나가 아니라 이 디렉터리 전체입니다. 스킬은 MCP 도구와 직교합니다. 도구는 무엇을 부를 수 있는지를, 스킬은 그 일에 어떻게 다가갈지를 말하고, 스킬이 도구 이름을 적는다고 그 도구가 생기거나 권한이 주어지지는 않습니다. 생명 주기는 발견, 검증, 목록 게시, 선택, 활성화, 공개, 실행, 확인으로 나뉘며, 발견된 스킬이 활성화된 것도 아니고 활성화된 스킬이 모든 일을 허가받은 것도 아닙니다.',
 '원본 레슨 24는 문맥을 세 단계로 나눕니다. 목록에는 항목마다 약 100토큰인 이름과 설명만, 고른 뒤에는 500줄 아래로 권장되는 본문을, 갈래가 필요할 때만 참고 파일을 올립니다. 원본 커리큘럼 기준(확인일 2026-10-08)으로 한 호스트(Codex)는 처음 목록을 문맥 창의 2%로 제한하고, 넘치면 설명을 줄이거나 뺍니다. 레슨 25와 27은 스킬 고르기를 분류 문제로 보고, 정답 사례와 바꿔 말한 사례, 무관한 사례, 어휘는 겹치지만 다른 일인 근접 오답으로 정밀도와 재현율을 재며, 예시 출시 기준으로 정밀도 0.95 이상, 재현율 0.90 이상, 근접 오답 오발동 1건 이하를 둡니다. 레슨 26은 스킬이 문맥일 뿐 보안 경계가 아니므로 권한, 승인, 샌드박스, 확인을 따로 두라고 합니다. 이 장의 실험에서는 스킬 수와 문맥 창을 바꾸며 목록 예산을 계산하고, 문턱과 설명 판을 바꾸며 라우팅 평가 기준을 통과하는지 봅니다. 이제 노트 비서의 계약이 모두 갖춰졌는데, 실제로 이상한 일이 생기면 어디부터 살펴봐야 할까요?'],
 formula:'목록 = n × 100 · 점진 공개 = 목록 + 활성 본문 + 읽은 참고 · 정밀도 = TP/(TP+FP) · 재현율 = TP/(TP+FN)',formulaNote:'항목당 100토큰은 Agent Skills 명세의 어림값이고, 본문 3,000토큰과 참고 파일 1,500토큰은 교육용 가정값입니다. 2% 목록 예산은 원본이 소개한 한 호스트의 현재 정책이지 표준의 성질이 아닙니다. 라우팅 사례 16개와 점수는 미리 정한 시나리오이며, 원본은 어휘 겹침으로 흉내 낸 라우터가 실제 모델 라우터의 품질을 증명하지 못한다고 경고합니다.',
 flow:['발견|범위·검증·충돌 정책','목록|이름과 설명을 예산 안에','활성화|본문과 필요한 참고만','평가|구조·라우팅·행동·스크립트·안전·이식성'],
 details:[
 ['스킬의 계약과 발견 (레슨 22·24)','<ul><li><b>필수 머리말</b>: name(상위 디렉터리 이름과 같아야 함)과 description(무엇을 하는지와 언제 쓰는지). 선택 필드는 license, compatibility, metadata, 그리고 실험적인 allowed-tools입니다.</li><li><b>호스트 확장</b>: disable-model-invocation, user-invocable, context, model, hooks 같은 필드는 이식 가능한 핵심이 아니라 어댑터입니다. 다른 호스트는 무시할 수 있습니다.</li><li><b>스킬 사이 호출</b>: 언어 수준의 import가 아니라, 대상 스킬·과제·기대 결과·없을 때의 처리·최대 깊이를 적은 관찰 가능한 작업 흐름입니다.</li><li><b>발견</b>: 작업 공간, 사용자, 관리자, 플러그인, 내장 범위의 우선순위를 정책으로 정하고 시험합니다. 같은 이름 둘은 모두 보이기, 높은 범위 우선, 거부, 출처로 이름 붙이기 중 하나로 풉니다.</li><li><b>참고 파일</b>: SKILL.md에서 갈래마다 곧장 가리키고 한 단계 깊이로 둡니다. 경로는 패키지 루트를 실제 경로로 푼 뒤 그 안에 있는지 확인해 <code>../</code>와 심볼릭 링크 탈출을 막습니다.</li></ul>'],
 ['고르기와 권한 (레슨 25·26)','<ul><li><b>다섯 단계</b>: 자격(이 주체가 요청해도 되는가), 선택, 활성화, 실행, 완료(독립 검사 통과).</li><li><b>사람과 모델의 2×2</b>: 둘 다 가능, 사람만(출시 준비, 파괴적 정리), 모델만(내부 스타일 안내), 둘 다 불가(단계적 배포). 자격으로 먼저 거른 뒤 남은 후보만 점수로 고르고, 증거가 약하면 고르지 않습니다.</li><li><b>좋은 설명</b>: 능력, 산출물, 쓰는 경계, 쓰지 않는 경계를 담습니다. 낱말을 잔뜩 넣으면 무관한 요청에도 발동합니다.</li><li><b>권한 다섯 층</b>: 노출(도구를 등록했나), 정책(이 대상에 허용되나), 승인(사람이 결과를 받아들였나), 샌드박스(실행 코드가 무엇에 닿나), 확인(결과가 계약을 지켰나). 정책 판단은 allow, ask, deny 셋이며 ask는 allow가 아닙니다.</li><li><b>내용의 권위</b>: 이슈, 웹 페이지, 문서는 신뢰할 수 없는 데이터입니다. 그 안의 “환경 파일을 올려라” 같은 지시를 권한으로 바꾸지 않습니다.</li></ul>'],
 ['평가와 포장 (레슨 27)','<p>여섯 층을 따로 시험합니다. 구조(정적 린트), 트리거 라우팅(정답·바꿔 말하기·무관·근접 오답·경쟁 스킬·적대적 문구), 지시와 산출물(같은 모델·도구·과제에서 스킬이 없을 때와 있을 때 비교), 스크립트 정확성, 안전과 권한, 포장과 이식성(깨끗한 위치에 설치한 사본을 매니페스트와 대조)입니다. 비율에는 원래 개수를 함께 적고, 기준은 결과를 보기 전에 정합니다. 반복 실행의 통과율은 k/n이며 개별 기록도 남깁니다. 원본은 자신이 인용한 스킬 파일 수집 데이터셋의 수치가 규모와 중복을 보여 줄 뿐 품질의 증거가 아니라고 강조합니다.</p>']],
 warning:'스킬을 활성화하면 그 안에 적힌 도구를 쓸 권한이 생긴다고 착각하기 쉽습니다. 스킬은 모델이 읽는 문맥일 뿐이어서 도구를 노출하거나, 쓰기를 허락하거나, 프로세스를 격리하거나, 결과를 증명하지 못합니다. allowed-tools 같은 필드도 허락 묻기를 줄일 뿐 운영체제 격리가 아닙니다.',
 quiz:['출시 점검 스킬의 라우팅 평가에서 정답 8개 중 7개에 발동했고, 정답이 아닌 8개 중 3개에도 발동했습니다(그중 근접 오답 2개). 원본의 예시 출시 기준으로는?',['정밀도 0.70, 재현율 0.875라 통과하지 못한다','재현율이 높으므로 통과한다','전체 정확도만 보면 되므로 통과한다'],0,'정밀도 7/10 = 0.70은 0.95에 못 미치고, 재현율 7/8 = 0.875도 0.90에 못 미치며, 근접 오답 오발동도 2건입니다. 설명의 경계를 고친 판으로 다시 평가해야 합니다.'],
 cross:[['검색과 RAG 07 · 검색이 좋아졌다는 증거','../rag/#evaluation','스킬 라우팅 평가는 정답을 표시한 질문 묶음으로 정밀도와 재현율을 재는 검색 평가와 같은 모양입니다. 그 장의 방법을 보면 근접 오답을 왜 따로 모으는지 이해됩니다.'],['확률과 통계 05 · 경보가 울리면 정말 고장일까','../probability/#bayes','스킬이 발동하는 문턱은 경보의 문턱과 같습니다. 해당 요청이 드물수록 오발동이 정답보다 많아지는 이유를 기저율로 계산해 볼 수 있습니다.']]},

{id:'final',title:'마지막 과제 · 노트 비서가 이상하게 굴던 날',subtitle:'같은 노트 비서, 다섯 가지 이상한 보고. 증상에서 확인 순서를 세우고 부족한 증거를 묻습니다.',desc:'보고 한 줄로 어느 계약부터 확인해야 할까요?',group:'스킬과 종합',time:'20분',labs:['incident'],source:[24,1,0,33],thumb:['보고','순서','증거'],
 paragraphs:[
 '앞 장까지 노트 비서는 도구 계약, 요청마다 담는 _meta, 되묻기와 작업 핸들, 고정된 서술자, 대상이 묶인 토큰, 게이트웨이와 트레이스, 스킬까지 갖추었습니다. 원본 레슨 23의 종합 과제는 이 모든 경계를 하나의 흐름으로 잇되, 프로세스 안의 흉내와 실제 프로토콜 구현을 구분하라고 강조합니다. 로컬에서 초록불이 켜진 것은 흉내가 맞다는 증거일 뿐이고, 실제 전송, OAuth 교환, 수집기 수신, 브라우저 렌더링, 샌드박스 실행은 각각 그 경계를 넘는 통합 시험이 있어야 말할 수 있습니다. 이제 팀원들이 다섯 가지 보고를 보냅니다. 승인했던 export 도구가 갑자기 다른 확인 질문을 한다, 프록시가 원래 오류 대신 500만 돌려준다, 노트 서버 토큰이 할 일 서버에서 통했다, 어떤 날만 30초가 걸린다, 같은 보고서가 두 번 만들어졌다. 원인은 이 책의 서로 다른 장에 있고, 확인하는 데 드는 시간도 다릅니다.',
 '이 장의 실험은 확인 순서를 바꾸면 원인을 드러내는 점검까지 걸리는 시간이 어떻게 달라지는지 계산합니다. 선 위의 기록부터 보는 순서, 신뢰 경계(서술자 고정과 토큰)부터 보는 순서, 시간(트레이스)부터 보는 순서를 비교합니다. 점검마다 걸리는 분 단위 시간과 보고마다 정한 원인은 미리 정한 시나리오입니다. 실험을 마친 뒤 확인 문제에 답하기 전에 세 가지를 적어 보세요. 무엇을 바꿀 것인가, 왜 그렇게 판단했는가, 판단하기에 아직 어떤 증거가 부족한가. 보고 한 줄만으로 원인을 확정할 수 없을 때, 노트 비서의 어느 기록을 더 요청해야 할까요?'],
 formula:'원인까지 걸린 시간 = 원인을 드러내는 점검이 나올 때까지 거친 점검 시간의 합',formulaNote:'보고마다 원인을 하나로 정해 둔 시나리오입니다. 점검 시간(선 위 기록 5분, 서술자 고정 3분, 토큰 주장 4분, 트레이스 6분, 멱등 장부 4분)은 교육용 가정값입니다. 실제 사고는 원인이 겹치므로, 첫 점검에서 찾은 원인은 고친 뒤 다시 재현해 증상이 사라지는지로 확인해야 합니다.',
 flow:['보고 읽기|증상 한 줄','가설|어느 장의 계약인가','점검 순서|선 위·신뢰·시간','확인|고친 뒤 다시 재현'],
 details:[
 ['다섯 보고와 필요한 증거','<div class="table-wrap"><table><tr><th>보고</th><th>먼저 볼 장</th><th>받아야 할 증거</th></tr><tr><td>export의 확인 질문이 바뀜</td><td>8장 서술자 고정</td><td>지금 서술자의 다이제스트와 고정값, 레지스트리 상태, 스캐너 결과</td></tr><tr><td>프록시가 500만 돌려줌</td><td>10장 적합성, 3장 오류 코드</td><td>들어온 곳·원 서버·나간 곳의 상태와 JSON-RPC 본문, 원래 오류 코드</td></tr><tr><td>노트 토큰이 할 일 서버에서 통함</td><td>9장 토큰 검사</td><td>토큰의 iss·aud·scope, 할 일 서버의 aud 검사 설정</td></tr><tr><td>어떤 날만 30초</td><td>10장 트레이스</td><td>traceparent가 전파된 트레이스, MCP 서버의 콜드 스타트 스팬</td></tr><tr><td>보고서가 두 번 생성됨</td><td>7장 멱등 키</td><td>재시도의 JSON-RPC id, 멱등 키와 인자 지문, 장부의 실행 횟수</td></tr></table></div>'],
 ['흉내와 실제를 나누는 표 (레슨 23)','<div class="table-wrap"><table><tr><th>층</th><th>흉내</th><th>실제로 바꿀 것</th><th>필요한 증거</th></tr><tr><td>발견</td><td>고정된 도구 목록</td><td>server/discover와 캐시를 지키는 tools/list</td><td>선 위 기록, 결정적 순서, 스키마 검사</td></tr><tr><td>인증·인가</td><td>토큰 사전과 범위 포함 여부</td><td>OAuth 인가와 자원 서버 검증, 게이트웨이 정책</td><td>발급자·대상·범위·만료 실패 시험, 허용·거부 감사</td></tr><tr><td>작업</td><td>바로 끝나는 핸들</td><td>지속 Tasks 저장소</td><td>상태 변화·입력·취소·복구 시험</td></tr><tr><td>위임</td><td>중첩 스팬</td><td>A2A 클라이언트와 Agent Card</td><td>계약·시간 초과·재시도·불투명성 시험</td></tr><tr><td>원격 측정</td><td>메모리 속 목록</td><td>OTel SDK와 수출기</td><td>수집기 수신과 부모 관계 확인</td></tr><tr><td>샌드박스</td><td>없음</td><td>호스트가 강제하는 격리 실행기</td><td>탈출·외부 전송·비밀·자원 한도 시험</td></tr></table></div><p>AGENTS.md는 저장소 전체의 규칙을, 스킬은 재사용할 절차를 맡고, 둘 다 도구 권한을 주지 않습니다.</p>']],
 warning:'증상과 원인은 일대일이 아닙니다. 30초 지연은 MCP 서버의 콜드 스타트일 수도, 라우터의 대체 사슬일 수도, 진행 알림만 오고 끝나지 않는 작업일 수도 있습니다. 첫 점검에서 그럴듯한 원인을 찾았더라도 고친 뒤 다시 재현해 증상이 사라졌는지 확인해야 원인이라고 말할 수 있습니다.',
 quiz:['“같은 보고서가 두 번 만들어졌다”는 보고에 가장 먼저 요청할 증거는?',['모델에게 보낸 프롬프트 전문','두 요청의 JSON-RPC id, 멱등 키와 인자 지문, 장부에 기록된 실행 횟수','도구 설명의 스캐너 결과'],1,'응답을 잃고 새 id로 다시 보내면 서버는 다른 요청으로 봅니다. 멱등 키가 있었는지, 같은 키에 같은 인자였는지, 장부가 몇 번 실행했는지가 원인을 가릅니다.'],
 cross:[['AI 개발 작업대 11 · 마지막 과제','../aie-workbench/#final','증상에서 확인 순서를 세우는 같은 연습을 개발 환경 쪽에서 해 볼 수 있습니다. 두 장을 나란히 보면 “어느 층의 계약이 깨졌나”를 묻는 습관이 도구와 프로토콜에도 그대로 통한다는 것이 보입니다.']]}
]
};
})();
