const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../js/math.js');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('one request: first token counted once',()=>{const r=M.metrics(400,20,32);assert.equal(r.total,1020);close(r.tps,32/1.02);assert.equal(M.metrics(400,20,1).gap,null);});
test('reducing TTFT is not proportional total speedup',()=>{assert.equal(M.metrics(200,20,32).total,820);});
test('asynchronous submission and completion differ',()=>{const r=M.timing(20,.02,2);close(r.enqueue,.4);close(r.event,40);close(r.wall,40.02);});
test('CPU submission can starve device',()=>{const r=M.timing(20,.2,.1);close(r.wall,4.1);close(r.event,3.9);});
test('pipeline obeys dependencies and serial work amount',()=>{for(const overlap of [false,true]){const r=M.pipeline(4,3,6,overlap);assert.equal(r.total,overlap?27:36);for(let i=0;i<4;i++)assert.ok(r.events[i*2+1].start>=r.events[i*2].end);}});
test('single chunk cannot overlap with itself',()=>assert.equal(M.pipeline(1,3,6,true).total,9));
test('copy bound pipeline and equal stage boundary',()=>{assert.equal(M.pipeline(4,6,3,true).total,27);assert.equal(M.pipeline(4,3,3,true).total,15);});
test('thread mapping covers every element exactly once',()=>{for(const n of [1,31,32,33,100,128,256])for(const b of [32,64,128,256]){const r=M.mapping(n,b);assert.ok(r.total>=n&&r.idle<b);assert.equal(r.total-r.idle,n);}assert.equal(M.mapping(100,64).idle,28);});
test('aligned, misaligned, strided sectors are 4,5,32',()=>{assert.equal(M.sectors(1,0).count,4);assert.equal(M.sectors(1,1).count,5);assert.equal(M.sectors(8,0).count,32);close(M.sectors(8,0).efficiency,.125);});
test('all stride patterns still request 128 distinct bytes',()=>{for(let s=1;s<=16;s++)for(let o=0;o<8;o++){const r=M.sectors(s,o);assert.equal(new Set(r.addresses).size,32);assert.ok(r.covered>=128);}});
test('SM resources and launch impossibility',()=>{assert.equal(M.occupancy(16,32).blocks,8);close(M.occupancy(16,32).ratio,1);close(M.occupancy(32,64).ratio,.5);assert.equal(M.occupancy(32,128).blocks,0);});
test('tile reuse reduces modeled loads without predicting time',()=>{close(M.occupancy(16,32).loads/M.occupancy(32,32).loads,2);});
test('roofline keeps units and detects inconsistent scope',()=>{const r=M.roofline(4,16,10);close(r.memory,8);close(r.compute,.32);close(r.tflops,1.6);close(r.gbps,400);assert.equal(M.roofline(4,16,2).consistent,false);});
test('fusion output agrees with separately materialized z',()=>{const r=M.fusion(4e6,1);assert.deepEqual(r.y,[0,0,0,0,1,2,3,4]);assert.equal(r.separate,80e6);assert.equal(r.fused,48e6);});
test('score storage is quadratic; fixed tile storage is fixed',()=>{const a=M.attention(2048,64),b=M.attention(8192,64);assert.equal(a.full,8*2**20);assert.equal(b.full/a.full,16);assert.equal(a.tile,16384);assert.equal(a.tile,b.tile);});
test('KV allocation rounds each request separately',()=>{const r=M.paging(513,16);assert.equal(r.used,899);assert.equal(r.allocated,944);assert.equal(r.waste,45);close(r.miB,132.75);assert.equal(M.paging(513,256).allocated,1536);});
test('KV boundary releases one full block',()=>{assert.equal(M.paging(513,16).allocated-M.paging(512,16).allocated,16);});
test('paging waste is bounded by number of requests times block',()=>{for(const n of [1,16,17,512,513,2048])for(const b of [16,64,256]){const r=M.paging(n,b);assert.ok(r.waste>=0&&r.waste<3*b);assert.ok(r.allocated<=r.reserved);}});
test('continuous scheduling preserves token work and completion order',()=>{const fixed=M.schedule(2,10,false),cont=M.schedule(2,10,true);assert.equal(fixed.total,110);assert.equal(cont.total,100);assert.deepEqual(fixed.ends,[20,60,90,110]);assert.deepEqual(cont.ends,[20,60,50,100]);assert.equal(cont.events.length,16);});
test('one slot and all slots remove policy distinction',()=>{for(const s of [1,4])assert.equal(M.schedule(s,10,true).total,M.schedule(s,10,false).total);});
test('at each schedule step active requests never exceed slots',()=>{for(const s of [1,2,3,4])for(const policy of [false,true]){const r=M.schedule(s,10,policy);for(let t=0;t<r.total;t+=10)assert.ok(r.events.filter(e=>e.start===t).length<=s);}});
test('parallel cost includes serial floor and communication',()=>{[18,10.96,8.4,9.04].forEach((t,i)=>close(M.parallel([1,2,4,8][i],.25,50).total,t));assert.equal(M.parallel(1,8,25).communication,0);assert.ok(M.parallel(2,8,25).total>18);});
test('only fused candidate passes default constraints',()=>assert.deepEqual(M.trials.map((_,i)=>M.decision(i,600,30,24).accepted),[false,true,false,false]));
test('stronger goal leaves no accepted candidate',()=>assert.ok(M.trials.every((_,i)=>!M.decision(i,500,30,24).accepted)));
test('quality cannot be traded away by loosening memory',()=>assert.equal(M.decision(3,800,50,32).accepted,false));
test('nearest-rank p95 uses nineteenth of twenty observations',()=>assert.equal(M.percentile(Array.from({length:20},(_,i)=>i+1),.95),19));
test('invalid divisor and missing variant produce explicit error',()=>{assert.throws(()=>M.roofline(4,16,0),RangeError);assert.throws(()=>M.parallel(2,1,0),RangeError);assert.throws(()=>M.decision(9,600,30,24),RangeError);});
