const test=require('node:test');
const assert=require('node:assert/strict');
const M=require('../js/math.js');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('8B × 16bit = 16 GB, and 8B × 4bit = 4 GB',()=>{assert.equal(M.weightBytes(8,16),16e9);assert.equal(M.weightBytes(8,4),4e9);});
test('GB and GiB conversion is explicit',()=>close(M.weightBytes(8,4)/M.GiB,3.725290298461914));
test('32B 4bit and 8B 16bit have equal raw weight storage',()=>assert.equal(M.weightBytes(32,4),M.weightBytes(8,16)));
test('linear layer known examples include bias',()=>{assert.equal(M.linearParams(4,3),15);assert.equal(M.linearParams(8,8),72);assert.equal(M.linearParams(4,4,2),40);});
test('toy KV baseline is exactly 1 GiB',()=>assert.equal(M.kvBytes({...M.models.toy,tokens:8192}),M.GiB));
test('KV doubles with context and triples with batch',()=>assert.equal(M.kvBytes({...M.models.toy,tokens:16384,batch:3}),6*M.GiB));
test('KV uses KV heads, not query heads',()=>assert.equal(M.kvBytes({...M.models.toy,kvHeads:4,tokens:8192}),.5*M.GiB));
test('official config examples yield 1.125 and .75 GiB',()=>{assert.equal(M.kvBytes({...M.models.q8,tokens:8192})/M.GiB,1.125);assert.equal(M.kvBytes({...M.models.q30,tokens:8192})/M.GiB,.75);});
test('zero stored tokens has no logical KV data',()=>assert.equal(M.kvBytes({...M.models.toy,tokens:0}),0));
test('matrix product independently known output',()=>assert.deepEqual(M.matrix(1).C,[[3,2,5,2],[4,3,2,5],[5,1,5,5],[4,2,4,4]]));
test('tiling preserves output and reduces ideal input loads',()=>{assert.deepEqual(M.matrix(1).C,M.matrix(4).C);assert.deepEqual([1,2,4].map(t=>M.matrix(t).loads),[128,64,32]);});
test('larger tiles require larger shared working space',()=>assert.equal(M.matrix(4).shared,128));
test('first output comes from prefill',()=>assert.deepEqual(M.phases(128,1),{prefill:128,decode:0,cached:128,uncached:128}));
test('16 output example accounts for G-1 decode steps',()=>{const p=M.phases(128,16);assert.equal(p.decode,15);assert.equal(p.cached,143);assert.equal(p.uncached,2168);});
test('more outputs cannot reduce projection position count',()=>{assert.ok(M.phases(128,32).cached>M.phases(128,16).cached);});
test('roofline memory bound example stays at 8ms when compute doubles',()=>{close(M.roofline({}).seconds,.008);close(M.roofline({compute:100}).seconds,.008);});
test('roofline changes to compute bound for large batch',()=>{const r=M.roofline({batch:128});assert.equal(r.bottleneck,'연산 처리량');close(r.math,.04096);});
test('roofline lower bound cannot be below either resource time',()=>{const r=M.roofline({batch:32});assert.ok(r.seconds>=r.memory&&r.seconds>=r.math);});
test('MoE storage grows with expert count while active stays fixed',()=>{assert.equal(M.moe(16,2).active,3);assert.equal(M.moe(64,2).active,3);assert.equal(M.moe(64,2).total,34);});
test('transfer example is 125ms, not 12.5ms',()=>{close(M.transfer(4,32),.125);assert.equal(M.transfer(0,32),0);});
test('quantized values stay on endpoints with fine precision reducing this fixture error',()=>{const x=[-.93,-.71,-.36,-.12,.14,.43,.68,.91];assert.ok(M.quantize(x,8).mse<M.quantize(x,2).mse);assert.deepEqual(M.quantize([-1,1],4).rounded,[-1,1]);});
test('final task exceeds 24GiB in 16bit and fits under stated 4bit assumptions',()=>{const a=M.budget({bits:16,tokens:32768,batch:4}),b=M.budget({bits:4,tokens:32768,batch:4});assert.equal(a.fits,false);assert.equal(b.fits,true);assert.equal(a.kv,16*M.GiB);assert.equal(a.total,36927352832);assert.equal(b.total,23727352832);});
test('changing weight precision does not change KV precision implicitly',()=>assert.equal(M.budget({bits:4}).kv,M.budget({bits:16}).kv));
test('increasing execution reserve can flip capacity verdict',()=>{assert.equal(M.budget({bits:4,tokens:32768,batch:4,reserve:4}).fits,false);});
test('invalid divisors and nonsensical inputs fail explicitly',()=>{assert.throws(()=>M.transfer(4,0),RangeError);assert.throws(()=>M.weightBytes(-1,4),RangeError);assert.throws(()=>M.moe(8,9),RangeError);assert.throws(()=>M.budget({model:'missing'}),RangeError);});
